### ISSUE TITLE
Migration of Sprout Forms notifications fails (recipients value is NULL)

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1026]
### Describe the bug

Running the Sprout Forms migration, it appears notifications are failing to be inserted. As the migration performs a transaction the process still continues but without the notification data being inserted into the notifications DB table.

I've taken one of the exceptions raised and cleaned it up as it has HTML formatting and encoded entities everywhere see #1023 

```
Notifications: Preparing to migrate 1 notifications. 
> Failed to migrate “Virtual Open Evening post event enquiry”. 
> #0 /app/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(PDOException, 'INSERT INTO craft_formie_notifications (formId, templateId, pdfTemplateId, name, enabled, subject, recipients, to, toConditions, cc, bcc, replyTo, replyToName, from, fromName, content, attachFiles, attachPdf, attachAssets, enableConditions, conditions, dateCreated, dateUpdated, uid) VALUES (587361, NULL, NULL, 'Virtual Open Evening post event enquiry', 1, 'Virtual Open Evening post event enquiry', NULL, 'events@nottinghamcollege.ac.uk', NULL, NULL, NULL, 'websiteteam@nottinghamcollege.ac.uk', NULL, 'websiteteam@nottinghamcollege.ac.uk', 'Nottingham College', '[{\"type\":\"paragraph\",\"content\":[]},{\"type\":\"paragraph\",\"content\":[{\"type\":\"variableTag\",\"attrs\":{\"label\":\"All Form Fields\",\"value\":\"{allFields}\"}}]}]', 0, 0, NULL, 0, NULL, '2022-08-03 08:07:15', '2022-08-03 08:07:15', '9eab4882-7305-4ef5-a818-d503895aa98a')') 
#1 /app/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('INSERT INTO craft_formie_notifications (formId, templateId, pdfTemplateId, name, enabled, subject, recipients, to, toConditions, cc, bcc, replyTo, replyToName, from, fromName, content, attachFiles, attachPdf, attachAssets, enableConditions, conditions, dateCreated, dateUpdated, uid) VALUES (587361, NULL, NULL, 'Virtual Open Evening post event enquiry', 1, 'Virtual Open Evening post event enquiry', NULL, 'events@nottinghamcollege.ac.uk', NULL, NULL, NULL, 'websiteteam@nottinghamcollege.ac.uk', NULL, 'websiteteam@nottinghamcollege.ac.uk', 'Nottingham College', '[{\"type\":\"paragraph\",\"content\":[]},{\"type\":\"paragraph\",\"content\":[{\"type\":\"variableTag\",\"attrs\":{\"label\":\"All Form Fields\",\"value\":\"{allFields}\"}}]}]', 0, 0, NULL, 0, NULL, '2022-08-03 08:07:15', '2022-08-03 08:07:15', '9eab4882-7305-4ef5-a818-d503895aa98a')') 
#2 /app/vendor/yiisoft/yii2/db/Schema.php(431): yii\db\Command->execute() 
#3 /app/vendor/yiisoft/yii2/db/ActiveRecord.php(604): yii\db\Schema->insert('{{%formie_notifications}}', Array) 
#4 /app/vendor/yiisoft/yii2/db/ActiveRecord.php(570): yii\db\ActiveRecord->insertInternal(NULL) 
#5 /app/vendor/yiisoft/yii2/db/BaseActiveRecord.php(676): yii\db\ActiveRecord->insert(false, NULL) 
#6 /app/vendor/verbb/formie/src/services/Notifications.php(153): yii\db\BaseActiveRecord->save(false) 
#7 /app/vendor/verbb/formie/src/migrations/MigrateSproutForms.php(376): verbb\formie\services\Notifications->saveNotification(verbb\formie\models\Notification) 
#8 /app/vendor/verbb/formie/src/migrations/MigrateSproutForms.php(92): verbb\formie\migrations\MigrateSproutForms->_migrateNotifications() 
#9 /app/vendor/craftcms/cms/src/db/Migration.php(53): verbb\formie\migrations\MigrateSproutForms->safeUp() 
#10 /app/vendor/verbb/formie/src/console/controllers/MigrateController.php(27): craft\db\Migration->up() 
#11 [internal function](): verbb\formie\console\controllers\MigrateController->actionMigrateSproutForms() 
#12 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) 
#13 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array) 
#14 /app/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('migrate-sprout-forms', Array) 
#15 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('migrate-sprout-forms', Array) 
#16 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('formie/migrate/migrate-sprout-forms', Array) 
#17 /app/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('formie/migrate/migrate-sprout-forms', Array) 
#18 /app/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('formie/migrate/migrate-sprout-forms', Array) 
#19 /app/vendor/craftcms/cms/src/console/Application.php(118): yii\console\Application->handleRequest(craft\console\Request) 
#20 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(craft\console\Request) 
#21 /app/craft(13): yii\base\Application->run()
```

Pasting the INSERT INTO command into an SQL editor to examine the command more closely, there's potentially an issue with the column names `to` and `from`. These may need to be quoted with backticks to allow the command to run correctly.

Without handling this currently produces an SQL error of:

```
Error Code: 1064. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'to, toConditions, cc, bcc, replyTo, replyToName, from, fromName, content, attach' at line 1
```

Example SQL that failed:

```
INSERT INTO craft_formie_notifications (formId, templateId, pdfTemplateId, name, enabled, subject, recipients, to, toConditions, cc, bcc, replyTo, replyToName, from, fromName, content, attachFiles, attachPdf, attachAssets, enableConditions, conditions, dateCreated, dateUpdated, uid) VALUES (587361, NULL, NULL, 'Virtual Open Evening post event enquiry', 1, 'Virtual Open Evening post event enquiry', NULL, 'events@nottinghamcollege.ac.uk', NULL, NULL, NULL, 'websiteteam@nottinghamcollege.ac.uk', NULL, 'websiteteam@nottinghamcollege.ac.uk', 'Nottingham College', '[{\"type\":\"paragraph\",\"content\":[]},{\"type\":\"paragraph\",\"content\":[{\"type\":\"variableTag\",\"attrs\":{\"label\":\"All Form Fields\",\"value\":\"{allFields}\"}}]}]', 0, 0, NULL, 0, NULL, '2022-08-03 08:07:15', '2022-08-03 08:07:15', '9eab4882-7305-4ef5-a818-d503895aa98a');
```

### Steps to reproduce

1. Run console command for migrating Sprout Forms data
2. Observe errors related to INSERT INTO commands for notifications

### Form settings

N/A migration from Sprout Forms (being created as new as part of migration)

### Craft CMS version

3.7.50

### Plugin version

1.6.5

### Multi-site?

No

**Comment by jamesmacwhite** [comment]
After applying backticks to the mentioned columns, this fixes the syntax error but then a further error with the recipients column is then thrown

```
Error Code: 1048. Column 'recipients' cannot be null
```

Looking at the Sprout Forms migration code I cannot see the recipients column being mapped

https://github.com/verbb/formie/blob/craft-3/src/migrations/MigrateSproutForms.php#L339-L351

As the SQL schema defines it as a enum, potentially a default value needs to be set in the migration.

It seems in this case it wants either the value `email` or `conditions`. Most likely from the migration it could be an email for compatibility.

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.6.5",
  "...": "..."
}
```

Then run `composer update`.

**Comment by jamesmacwhite** [comment]
@engram-design Thanks for this, wouldn't there still be an issue with the SQL query overall because it has two columns using reserved words i,e. "to" and "from", these need to be wrapped with backticks, otherwise the SQL syntax fails.

https://dev.mysql.com/doc/refman/8.0/en/keywords.html

**Comment by engram-design** [comment]
What version of MySQL are you on? Doesn't seem to throw an error on my end!

**Comment by jamesmacwhite** [comment]
MySQL 8 with strict mode. I'll double check if the syntax error is purely because I copied the original command from the console output when testing which led to me finding the NULL recipient issue. Will report back soon

**Comment by engram-design** [comment]
I'm 99% sure Yii will take care of the escaping, but happy to be proven wrong.

**Comment by jamesmacwhite** [comment]
I've confirmed the issue was around the recipients value being NULL, no errors anymore, the name of to and from column was purely due to copying the raw SQL from the console output so a bit of a red herring! Apologies, the main fix is the recipients NULL value which is now fixed.

**Comment by jamesmacwhite** [comment]
Fixed in https://github.com/verbb/formie/commit/229eeb327f89498e92598e8c93f172628dc356bc
