### ISSUE TITLE
Incorrect table name exception when creating very long group field name

### ISSUE THREAD

**Issue by nickcobley** [verbb/formie#135]
**Description**
I had a user create a very very long label for a Group Advanced Field and multiline text form within the group, which throws this error on save

```
2020-09-24 10:29:27 [-][1][-][error][yii\db\Exception] PDOException: SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name 'craft_fmc_11246_imareallyreallyreallynoreallyimareallyreallyreallyextralar' in /var/www/vhosts/*/vendor/yiisoft/yii2/db/Command.php:1293

Stack trace:
#0 /var/www/vhosts/*/vendor/yiisoft/yii2/db/Command.php(1293): PDOStatement->execute()
#1 /var/www/vhosts/*/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute('DROP TABLE `cra...')
#2 /var/www/vhosts/*/vendor/verbb/formie/src/services/NestedFields.php(222): yii\db\Command->execute()
#3 /var/www/vhosts/*/vendor/verbb/formie/src/base/NestedFieldTrait.php(320): verbb\formie\services\NestedFields->deleteNestedField(Object(verbb\formie\fields\formfields\Group))
#4 /var/www/vhosts/*/vendor/craftcms/cms/src/services/Fields.php(941): verbb\formie\fields\formfields\Group->beforeApplyDelete()
#5 /var/www/vhosts/*/vendor/craftcms/cms/src/services/Fields.php(888): craft\services\Fields->applyFieldDelete('42a568ab-4689-4...')
#6 /var/www/vhosts/*/vendor/verbb/formie/src/services/Forms.php(141): craft\services\Fields->deleteField(Object(verbb\formie\fields\formfields\Group))
#7 /var/www/vhosts/*/vendor/verbb/formie/src/controllers/FormsController.php(134): verbb\formie\services\Forms->saveForm(Object(verbb\formie\elements\Form))
#8 [internal function]: verbb\formie\controllers\FormsController->actionSave()
#9 /var/www/vhosts/*/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /var/www/vhosts/*/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#11 /var/www/vhosts/*/vendor/craftcms/cms/src/web/Controller.php(189): yii\base\Controller->runAction('save', Array)
#12 /var/www/vhosts/*/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save', Array)
#13 /var/www/vhosts/*/vendor/craftcms/cms/src/web/Application.php(285): yii\base\Module->runAction('formie/forms/sa...', Array)
#14 /var/www/vhosts/*/vendor/craftcms/cms/src/web/Application.php(588): craft\web\Application->runAction('formie/forms/sa...', Array)
#15 /var/www/vhosts/*/vendor/craftcms/cms/src/web/Application.php(264): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#16 /var/www/vhosts/*/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /var/www/vhosts/*/httpdocs/index.php(21): yii\base\Application->run()
#18 {main}
```

**Steps to reproduce**
1. Create an new form
2. Add a Group field, label it "I'm a really really really, no really I'm a really really really extra largely long group field label"
3. Add a Multiline Text field, label it "You thought that group field label was really reall really long... nah this is long, I'm a mysql breaking masterpiece"
4. Hit save, it should fail to save and throw an exception

Side note in troubleshooting this. If I remove the offending fields, it will still fail to save with the same exception, only saving as a copy would allow the form to save. 

No rush to fix this one, worked around here, unlikely to hit the issue anytime soon. 

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.2.17
- Craft version: 3.5.11.1
- Multi-site: No

**Comment by engram-design** [comment]
Fixed in [1.2.18](https://github.com/verbb/formie/releases/tag/1.2.18)
