### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by mkrigsman** [verbb/formie#1355]
### Question

I am getting this error. Any ideas what the problem is? Thanks!

2023-03-16 12:12:47 [web.ERROR] [TypeError] verbb\formie\services\Forms::getFormByHandle(): Argument #1 ($handle) must be of type string, null given, called in /var/www/vendor/verbb/formie/src/controllers/FormsController.php on line 384 {"trace":["#0 /var/www/vendor/verbb/formie/src/controllers/FormsController.php(384): verbb\\formie\\services\\Forms->getFormByHandle()","#1 [internal function]: verbb\\formie\\controllers\\FormsController->actionRefreshTokens()","#2 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()","#3 /var/www/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams()","#4 /var/www/vendor/yiisoft/yii2/base/Module.php(552): yii\\base\\Controller->runAction()","#5 /var/www/vendor/craftcms/cms/src/web/Application.php(302): yii\\base\\Module->runAction()","#6 /var/www/vendor/craftcms/cms/src/web/Application.php(627): craft\\web\\Application->runAction()","#7 /var/www/vendor/craftcms/cms/src/web/Application.php(281): craft\\web\\Application->_processActionRequest()","#8 /var/www/vendor/yiisoft/yii2/base/Application.php(384): craft\\web\\Application->handleRequest()","#9 /var/www/web/index.php(12): yii\\base\\Application->run()","#10 {main}"],"memory":2981664,"exception":"[object] (TypeError(code: 0): verbb\\formie\\services\\Forms::getFormByHandle(): Argument #1 ($handle) must be of type string, null given, called in /var/www/vendor/verbb/formie/src/controllers/FormsController.php on line 384 at /var/www/vendor/verbb/formie/src/services/Forms.php:65)"}

**Comment by engram-design** [comment]
I really need to know your Formie version to double check this, but assuming it's the latest 2.x version, this seems to be related to fetching refresh tokens. Are you calling this in your templates? This error shows that the `form` parameter is missing from the request.

**Comment by mkrigsman** [comment]
We are using the latest version 2.0.24. Will need to ask the developer. Are there any other questions I should ask him? I should mention that Formie seems to be functioning properly aside from this error.

**Comment by engram-design** [comment]
It would be something to do with the template call when rendering Formie, very likely related to refreshing CSRF tokens as described [here](https://verbb.io/craft-plugins/formie/docs/template-guides/cached-forms#csrf-token)

**Comment by mkrigsman** [comment]
Thanks so much. Will ask the developer and come back here if we cannot figure it out.
