### ISSUE TITLE
formie/settings/crm/new

### ISSUE THREAD

**Issue by alexanderbuergin** [verbb/formie#1415]
I have tried to create a new integration with Formie, but the following error occurs:

By accessing the URL `formie/settings/crm/new` I get that error:
```
craft\web\twig\TemplateLoaderException: Das Template „formie/integrations/crm/kapsel/_plugin-settings“ konnte nicht gefunden werden. in /home/patricku/public_html/site/v1-craft/vendor/verbb/formie/src/templates/settings/integrations/_edit.html:100
Stack trace:
#0 /home/patricku/public_html/site/v1-craft/vendor/craftcms/cms/src/web/twig/TemplateLoader.php(69): craft\web\twig\TemplateLoader->_resolveTemplate('formie/integrat...')
#1 /home/patricku/public_html/site/v1-craft/vendor/twig/twig/src/Environment.php(261): craft\web\twig\TemplateLoader->getCacheKey('formie/integrat...')
#2 /home/patricku/public_html/site/v1-craft/vendor/twig/twig/src/Environment.php(309): Twig\Environment->getTemplateClass('formie/integrat...')
#3 /home/patricku/public_html/site/v1-craft/vendor/twig/twig/src/Environment.php(277): Twig\Environment->load('formie/integrat...')
#4 /home/patricku/public_html/site/v1-craft/vendor/craftcms/cms/src/web/View.php(456): Twig\Environment->render('formie/integrat...', Array)
#5 /home/patricku/public_html/site/v1-craft/vendor/verbb/formie/src/base/Crm.php(49): craft\web\View->renderTemplate('formie/integrat...', Array)
#6 /home/patricku/public_html/site/v1-craft/vendor/twig/twig/src/Extension/CoreExtension.php(1607): verbb\formie\base\Crm->getSettingsHtml()
#7 /home/patricku/public_html/site/v1-craft/vendor/craftcms/cms/src/helpers/Template.php(146): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(verbb\formie\integrations\crm\Capsule), 'getSettingsHtml', Array, 'method', false, false)
#8 /home/patricku/public_html/site/v1-craft/storage/runtime/compiled_templates/d6/d60bc8b0e4189ba48e70dc60312e6968.php(217): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(verbb\formie\integrations\crm\Capsule), 'getSettingsHtml', Array, 'method')
#9 /home/patricku/public_html/site/v1-craft/vendor/twig/twig/src/Template.php(171): __TwigTemplate_5ce6a750864a146373bb7d9ac434075f->block_content(Array, Array)
#10 /home/patricku/public_html/site/v1-craft/storage/runtime/compiled_templates/27/27fb1c06fa7acdd3c2613a63d176b801.php(592): Twig\Template->displayBlock('content', Array, Array)
#11 /home/patricku/public_html/site/v1-craft/vendor/twig/twig/src/Template.php(171): __TwigTemplate_767c64576023cc9908303ff6f291096e->block_main(Array, Array)
#12 /home/patricku/public_html/site/v1-craft/storage/runtime/compiled_templates/27/27fb1c06fa7acdd3c2613a63d176b801.php(376): Twig\Template->displayBlock('main', Array, Array)
#13 /home/patricku/public_html/site/v1-craft/vendor/twig/twig/src/Template.php(171): __TwigTemplate_767c64576023cc9908303ff6f291096e->block_body(Array, Array)
#14 /home/patricku/public_html/site/v1-craft/storage/runtime/compiled_templates/45/455f671d4b1e30ad8fc088372c073851.php(94): Twig\Template->displayBlock('body', Array, Array)
#15 /home/patricku/public_html/site/v1-craft/vendor/twig/twig/src/Template.php(394): __TwigTemplate_ef3d083ad22e158b7cc28a3e20491126->doDisplay(Array, Array)
#16 /home/patricku/public_html/site/v1-craft/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#17 /home/patricku/public_html/site/v1-craft/storage/runtime/compiled_templates/65/65385c29384f05b6563cfcf9736d55f8.php(56): Twig\Template->display(Array, Array)
#18 /home/patricku/public_html/site/v1-craft/vendor/twig/twig/src/Template.php(394): __TwigTemplate_8a6a671b1ed8d5c370194aa96fb11e5c->doDisplay(Array, Array)
#19 /home/patricku/public_html/site/v1-craft/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#20 /home/patricku/public_html/site/v1-craft/storage/runtime/compiled_templates/27/27fb1c06fa7acdd3c2613a63d176b801.php(179): Twig\Template->display(Array, Array)
#21 /home/patricku/public_html/site/v1-craft/vendor/twig/twig/src/Template.php(394): __TwigTemplate_767c64576023cc9908303ff6f291096e->doDisplay(Array, Array)
#22 /home/patricku/public_html/site/v1-craft/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#23 /home/patricku/public_html/site/v1-craft/storage/runtime/compiled_templates/0f/0fe167259d41761bff470433462842c2.php(50): Twig\Template->display(Array, Array)
#24 /home/patricku/public_html/site/v1-craft/vendor/twig/twig/src/Template.php(394): __TwigTemplate_4949dea5622b31d6a7eb64036760db78->doDisplay(Array, Array)
#25 /home/patricku/public_html/site/v1-craft/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#26 /home/patricku/public_html/site/v1-craft/storage/runtime/compiled_templates/d6/d60bc8b0e4189ba48e70dc60312e6968.php(100): Twig\Template->display(Array, Array)
#27 /home/patricku/public_html/site/v1-craft/vendor/twig/twig/src/Template.php(394): __TwigTemplate_5ce6a750864a146373bb7d9ac434075f->doDisplay(Array, Array)
#28 /home/patricku/public_html/site/v1-craft/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#29 /home/patricku/public_html/site/v1-craft/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#30 /home/patricku/public_html/site/v1-craft/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#31 /home/patricku/public_html/site/v1-craft/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#32 /home/patricku/public_html/site/v1-craft/vendor/craftcms/cms/src/web/View.php(456): Twig\Environment->render('formie/settings...', Array)
#33 /home/patricku/public_html/site/v1-craft/vendor/craftcms/cms/src/web/View.php(509): craft\web\View->renderTemplate('formie/settings...', Array)
#34 /home/patricku/public_html/site/v1-craft/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(56): craft\web\View->renderPageTemplate('formie/settings...', Array, 'cp')
#35 /home/patricku/public_html/site/v1-craft/vendor/yiisoft/yii2/web/Response.php(1098): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#36 /home/patricku/public_html/site/v1-craft/vendor/craftcms/cms/src/web/Response.php(286): yii\web\Response->prepare()
#37 /home/patricku/public_html/site/v1-craft/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#38 /home/patricku/public_html/site/v1-craft/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#39 /home/patricku/public_html/site/v1-craft/web/index.php(21): yii\base\Application->run()
#40 {main}
```

### Steps to reproduce
Reinstall the plugin and the full craft CMS installation.

### phpversion
8.2.3

### Craft CMS version
4.4.8

### Plugin version
2.0.28

### Multi-site?
No

**Comment by engram-design** [comment]
It looks like something is translating `capsule` to `kapsel` and messing with the `Capsule` CRM integration where the path is translating, causing this 404 error. Can you confirm if this is something you're doing? Or is it a custom integration on your end?
