### ISSUE TITLE
Undefined array key after Freeform migration

### ISSUE THREAD

**Issue by LauraStatik** [verbb/formie#1439]
### Describe the bug

We managed to migrate all the forms from Freeform. When trying to access the Formie submissions (and sent notifications), we get Undefined array key referring to Freeform (in /vendor/solspace/craft-freeform/packages/plugin/src/Bundles/Submissions/CustomSourceFields.php)

When disabling the Freeform plugin, we do have access to the Formie submissions and sent notifications. Is there a possibility of running both plugins at the same time and have access to the submissions and sent notifications?

### Steps to reproduce

1. Use the migration tool to migrate forms and submissions from Freeform
2. Open tab Submissions in Formie

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

4.3.2

### Plugin version

2.0.28

### Multi-site?

Yes

### Additional context

Freeform plugin version: 4.0.7

**Comment by engram-design** [comment]
You should be able to run both plugins at the same time. There’s been one or two conflicts in the past, but these should’ve been fixed a while back. https://github.com/solspace/craft-freeform/pull/586

Can you send through the full stack trace of the error so I can trace it back? Difficult to say whether it’s a Freeform or Formie issue.

**Comment by LauraStatik** [comment]
@engram-design Here you go: 
```
yii\base\ErrorException: Undefined array key 260880 in /Users/statik/Sites/intcra/vendor/solspace/craft-freeform/packages/plugin/src/Bundles/Submissions/CustomSourceFields.php:48
Stack trace:
#0 /Users/statik/Sites/intcra/vendor/craftcms/cms/src/web/ErrorHandler.php(79): yii\base\ErrorHandler->handleError(2, 'Undefined array...', '/Users/statik/S...', 48)
#1 /Users/statik/Sites/intcra/vendor/solspace/craft-freeform/packages/plugin/src/Bundles/Submissions/CustomSourceFields.php(48): craft\web\ErrorHandler->handleError(2, 'Undefined array...', '/Users/statik/S...', 48)
#2 [internal function]: Solspace\Freeform\Bundles\Submissions\CustomSourceFields->handleCustomTableAttributes(Object(craft\events\DefineSourceTableAttributesEvent))
#3 /Users/statik/Sites/intcra/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(craft\events\DefineSourceTableAttributesEvent))
#4 /Users/statik/Sites/intcra/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger('craft\\services\\...', 'defineSourceTab...', Object(craft\events\DefineSourceTableAttributesEvent))
#5 /Users/statik/Sites/intcra/vendor/craftcms/cms/src/services/ElementSources.php(346): yii\base\Component->trigger('defineSourceTab...', Object(craft\events\DefineSourceTableAttributesEvent))
#6 /Users/statik/Sites/intcra/vendor/twig/twig/src/Extension/CoreExtension.php(1607): craft\services\ElementSources->getSourceTableAttributes('verbb\\formie\\el...', 'form:260880')
#7 /Users/statik/Sites/intcra/vendor/craftcms/cms/src/helpers/Template.php(110): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\services\ElementSources), 'getSourceTableA...', Array, 'method', false, false)
#8 /Users/statik/Sites/intcra/storage/runtime/compiled_templates/8a/8a4d49232ea6c4aed628b3ee5d2164bc.php(220): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\services\ElementSources), 'getSourceTableA...', Array, 'method')
#9 /Users/statik/Sites/intcra/vendor/twig/twig/src/Extension/CoreExtension.php(1202): __TwigTemplate_54a772c6e1d9d47d52d9040a44ee9841->macro_sourceLink('form:260880', Array, true, 'verbb\\formie\\el...', Array, Array)
#10 /Users/statik/Sites/intcra/storage/runtime/compiled_templates/8a/8a4d49232ea6c4aed628b3ee5d2164bc.php(128): twig_call_macro(Object(__TwigTemplate_54a772c6e1d9d47d52d9040a44ee9841), 'macro_sourceLin...', Array, 101, Array, Object(Twig\Source))
#11 /Users/statik/Sites/intcra/vendor/twig/twig/src/Template.php(394): __TwigTemplate_54a772c6e1d9d47d52d9040a44ee9841->doDisplay(Array, Array)
#12 /Users/statik/Sites/intcra/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#13 /Users/statik/Sites/intcra/storage/runtime/compiled_templates/69/691af618bcc68d7efbaee674c1be0be1.php(106): Twig\Template->display(Array)
#14 /Users/statik/Sites/intcra/vendor/twig/twig/src/Template.php(171): __TwigTemplate_c6c817b36fd64295d2deb1d93ede27dd->block_sidebar(Array, Array)
#15 /Users/statik/Sites/intcra/vendor/twig/twig/src/Template.php(243): Twig\Template->displayBlock('sidebar', Array, Array, true)
#16 /Users/statik/Sites/intcra/storage/runtime/compiled_templates/5f/5f24b992b4ad68bdcb537b1091437fe8.php(95): Twig\Template->renderBlock('sidebar', Array, Array)
#17 /Users/statik/Sites/intcra/vendor/twig/twig/src/Template.php(394): __TwigTemplate_bd32739e2023486acf61645f40695336->doDisplay(Array, Array)
#18 /Users/statik/Sites/intcra/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#19 /Users/statik/Sites/intcra/storage/runtime/compiled_templates/69/691af618bcc68d7efbaee674c1be0be1.php(71): Twig\Template->display(Array, Array)
#20 /Users/statik/Sites/intcra/vendor/twig/twig/src/Template.php(394): __TwigTemplate_c6c817b36fd64295d2deb1d93ede27dd->doDisplay(Array, Array)
#21 /Users/statik/Sites/intcra/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#22 /Users/statik/Sites/intcra/storage/runtime/compiled_templates/16/16120894fe2a337904da34e51262ce0a.php(93): Twig\Template->display(Array, Array)
#23 /Users/statik/Sites/intcra/vendor/twig/twig/src/Template.php(394): __TwigTemplate_eaf219353c610a00b9afa5ed561703fd->doDisplay(Array, Array)
#24 /Users/statik/Sites/intcra/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#25 /Users/statik/Sites/intcra/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#26 /Users/statik/Sites/intcra/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#27 /Users/statik/Sites/intcra/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#28 /Users/statik/Sites/intcra/vendor/craftcms/cms/src/web/View.php(451): Twig\Environment->render('formie/submissi...', Array)
#29 /Users/statik/Sites/intcra/vendor/craftcms/cms/src/web/View.php(504): craft\web\View->renderTemplate('formie/submissi...', Array)
#30 /Users/statik/Sites/intcra/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(56): craft\web\View->renderPageTemplate('formie/submissi...', Array, 'cp')
#31 /Users/statik/Sites/intcra/vendor/yiisoft/yii2/web/Response.php(1098): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#32 /Users/statik/Sites/intcra/vendor/craftcms/cms/src/web/Response.php(286): yii\web\Response->prepare()
#33 /Users/statik/Sites/intcra/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#34 /Users/statik/Sites/intcra/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#35 /Users/statik/Sites/intcra/public/index.php(13): yii\base\Application->run()
#36 {main}
```

**Comment by engram-design** [comment]
Hmm, that's a new error I haven't seen yet. I'll see how I go at reproducing it. What sort of fields did your Freeform form have? It's probably no useful to send through an export of the Formie form, but I don't think there's an easy export from Freefom you can send through for me to replicate.

I'll see what I can do.

**Comment by LauraStatik** [comment]
We have several forms combining the following fields:
- Text
- Textarea
- Email
- Checkbox
- Radio
- Select
- File upload
- Hidden fields

Does this sufficiently answer your question?
Many thanks!

**Comment by engram-design** [comment]
This error seems to be coming from Freeform, so it's likely an issue there.
