### ISSUE TITLE
craft\web\ServiceUnavailableHttpException after Formie installation

### ISSUE THREAD

**Issue by alexanderbuergin** [verbb/formie#1733]
### Describe the bug

Hello Verbb Team
We have the problem that Formie cannot be installed in a Craft CMS instance.

The installation runs normally, after we add Formie with composer require "verbb/formie" to the installation and then query the website again we get this error: We have tested it on several servers.

```

craft\web\ServiceUnavailableHttpException in /Users/office/_localhost/ca/vendor/craftcms/cms/src/web/Application.php:699
Stack trace:
#0 /Users/office/_localhost/ca/vendor/craftcms/cms/src/web/Application.php(262): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#1 /Users/office/_localhost/ca/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#2 /Users/office/_localhost/ca/web/index.php(23): yii\base\Application->run()
#3 {main}
Copy StacktraceSearch StackoverflowSearch GoogleException
HTTP 503 – Service Unavailable – craft\web\ServiceUnavailableHttpException
1. in /Users/office/_localhost/ca/vendor/craftcms/cms/src/web/Application.phpat line 699
690691692693694695696697698699700701702703704705706707708                $actionSegments === ['app', 'migrate'] ||
                $actionSegments === ['pluginstore', 'install', 'migrate']
            ) {
                return $this->runAction(implode('/', $actionSegments));
            }
        }
 
        // If an exception gets throw during the rendering of the 503 template, let
        // TemplatesController->actionRenderError() take care of it.
        throw new ServiceUnavailableHttpException();
    }
 
    /**
     * @inheritdoc
     */
    public function end($status = 0, $response = null)
    {
        // If we're already sending a template response, just throw an exception
        if (
2. in /Users/office/_localhost/ca/vendor/craftcms/cms/src/web/Application.php at line 262– craft\web\Application::_processUpdateLogic(craft\web\Request)
256257258259260261262263264265266267268                    Craft::$app->getErrorHandler()->logException($e);
                }
            }
 
            // Check if a plugin needs to update the database.
            if ($this->getUpdates()->getIsPluginUpdatePending()) {
                return $this->_processUpdateLogic($request) ?: $this->getResponse();
            }
 
            // If this is a plugin template request, make sure the user has access to the plugin
            // If this is a non-login, non-validate, non-setPassword control panel request, make sure the user has access to the control panel
            if (
                $request->getIsCpRequest() &&
3. in /Users/office/_localhost/ca/vendor/yiisoft/yii2/base/Application.php at line 384– craft\web\Application::handleRequest(craft\web\Request)
4. in /Users/office/_localhost/ca/web/index.php at line 23– yii\base\Application::run()
17181920212223    Dotenv\Dotenv::createUnsafeMutable(CRAFT_BASE_PATH)->safeLoad();
}
 
// Load and run Craft
define('CRAFT_ENVIRONMENT', getenv('ENVIRONMENT') ?: 'production');
$app = require CRAFT_VENDOR_PATH.'/craftcms/cms/bootstrap/web.php';
$app->run();
$_COOKIE = [
    'cookie_consent_user_consent_token' => 'HOQ1f8hxaCGz',
    'cookie_consent_user_accepted' => 'true',
    'CSRF' => '9a5a56d8a659322093dd1af787b3eb202c1dffb30cd8a8423c4c7732436dc112a:2:{i:0;s:4:"CSRF";i:1;s:40:"IsVCqwnq4dFa5lS9GdH0XCYrOsjqtAYwPHb5E2_A";}',
    'cookie_consent_level' => '{"strictly-necessary":true,"functionality":true,"tracking":true,"targeting":true}',
];
Yii Framework
2024-02-20, 23:30:48

Apache/2.4.54 (Unix) OpenSSL/1.0.2u mod_wsgi/3.5 Python/2.7.18 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.11 Perl/v5.30.1

Yii Framework/2.0.48.1
```

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Craft CMS version

4.7

### Plugin version

2.1.4

### Multi-site?

Yes

**Comment by engram-design** [comment]
I believe the `ServiceUnavailableHttpException` might point to a migration needing to be run? If you visit your control panel, is there any prompt for a migration to run? You should be doing that on a local development install though.

**Comment by alexanderbuergin** [comment]
Then I get the same error. I found this in the log.

Sure, the test was on a test machine ;)

```
Describe what happened here.

-----------------------------------------------------------

Database Exception: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint
The SQL being executed was: ALTER TABLE `formie_payments` ADD CONSTRAINT `fk_kdvuldgefwhxubmhcshsmnfywjbmnmtlwdcv` FOREIGN KEY (`submissionId`) REFERENCES `formie_submissions` (`id`) ON DELETE CASCADE

Migration: verbb\formie\migrations\m220530_000000_payments

Output:

    > create table {{%formie_payments}} ... done (time: 0.085s)
    > create index idx_zusafvhzblyparkexsdbfoqsxztpnmbiynww on {{%formie_payments}} (integrationId) ... done (time: 0.028s)
    > create index idx_scdnhdqxmcvardxisvwljadshmcghkuhwejs on {{%formie_payments}} (fieldId) ... done (time: 0.045s)
    > create index idx_viajldaczkrfvcoycejbcwvitxuepfpiojpv on {{%formie_payments}} (reference) ... done (time: 0.044s)
    > add foreign key fk_kdvuldgefwhxubmhcshsmnfywjbmnmtlwdcv: {{%formie_payments}} (submissionId) references {{%formie_submissions}} (id) ...Exception: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint
The SQL being executed was: ALTER TABLE `formie_payments` ADD CONSTRAINT `fk_kdvuldgefwhxubmhcshsmnfywjbmnmtlwdcv` FOREIGN KEY (`submissionId`) REFERENCES `formie_submissions` (`id`) ON DELETE CASCADE (/Users/office/_localhost/ca/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /Users/office/_localhost/ca/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `fo...')
#1 /Users/office/_localhost/ca/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('ALTER TABLE `fo...')
#2 /Users/office/_localhost/ca/vendor/yiisoft/yii2/db/Migration.php(466): yii\db\Command->execute()
#3 /Users/office/_localhost/ca/vendor/craftcms/cms/src/db/Migration.php(433): yii\db\Migration->addForeignKey('fk_kdvuldgefwhx...', '{{%formie_payme...', Array, '{{%formie_submi...', Array, 'CASCADE', NULL)
#4 /Users/office/_localhost/ca/vendor/verbb/formie/src/migrations/m220530_000000_payments.php(104): craft\db\Migration->addForeignKey(NULL, '{{%formie_payme...', Array, '{{%formie_submi...', Array, 'CASCADE', NULL)
#5 /Users/office/_localhost/ca/vendor/craftcms/cms/src/db/Migration.php(49): verbb\formie\migrations\m220530_000000_payments->safeUp()
#6 /Users/office/_localhost/ca/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#7 /Users/office/_localhost/ca/vendor/craftcms/cms/src/db/MigrationManager.php(149): craft\db\MigrationManager->migrateUp(Object(verbb\formie\migrations\m220530_000000_payments))
#8 /Users/office/_localhost/ca/vendor/craftcms/cms/src/services/Updates.php(252): craft\db\MigrationManager->up()
#9 /Users/office/_localhost/ca/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(493): craft\services\Updates->runMigrations(Array)
#10 /Users/office/_localhost/ca/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#11 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#12 /Users/office/_localhost/ca/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /Users/office/_localhost/ca/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#14 /Users/office/_localhost/ca/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('migrate', Array)
#15 /Users/office/_localhost/ca/vendor/craftcms/cms/src/web/Application.php(307): yii\base\Module->runAction('updater/migrate', Array)
#16 /Users/office/_localhost/ca/vendor/craftcms/cms/src/web/Application.php(695): craft\web\Application->runAction('updater/migrate')
#17 /Users/office/_localhost/ca/vendor/craftcms/cms/src/web/Application.php(264): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#18 /Users/office/_localhost/ca/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /Users/office/_localhost/ca/web/index.php(23): yii\base\Application->run()
#20 {main}

```

**Comment by engram-design** [comment]
It seems like you might've had Formie installed previously, if this migration is being run? Can you confirm if this is a fresh install of Formie, or an update?

If it's a fresh install of the plugin, then there's remnants of it being installed previously. There's something in your system that's preventing a foreign key on the `formie_payments` database table from being added.

**Comment by alexanderbuergin** [comment]
We have taken over the project, so we cannot say 100%. But there are Formie tables in the database, so the answer is that Formie was probably already installed in the past. Bun then was uninstalled as it seams.

I have removed the tables from the database to see if this solves the problem, unfortunately without success.

**Comment by engram-design** [comment]
It's very likely that it wasn't uninstalled properly, so there's data still remaining for Formie. Steps are:
- Remove a  `formie_*` and `fmc_*` db tables
- Remove `formie` row in `plugins` db table
- Remove any references to `formie` in `projectconfig` db table
- Remove any references to `formie` in `migrations` db table

**Comment by alexanderbuergin** [comment]
After trying it in different variants i still get this error and can't update the DB:


```
Database Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.ca.formie_stencils' doesn't exist
The SQL being executed was: ALTER TABLE `formie_stencils` ADD `submitActionEntryId` int(11) AFTER `templateId`

Migration: verbb\formie\migrations\m220420_000000_stencil_add_entryid

Output:

    > add column submitActionEntryId integer AFTER `templateId` to table {{%formie_stencils}} ...Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.ca.formie_stencils' doesn't exist
The SQL being executed was: ALTER TABLE `formie_stencils` ADD `submitActionEntryId` int(11) AFTER `templateId` (/Users/office/_localhost/ca/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /Users/office/_localhost/ca/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `fo...')
#1 /Users/office/_localhost/ca/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('ALTER TABLE `fo...')
#2 /Users/office/_localhost/ca/vendor/yiisoft/yii2/db/Migration.php(376): yii\db\Command->execute()
#3 /Users/office/_localhost/ca/vendor/verbb/formie/src/migrations/m220420_000000_stencil_add_entryid.php(14): yii\db\Migration->addColumn('{{%formie_stenc...', 'submitActionEnt...', Object(craft\db\mysql\ColumnSchemaBuilder))
#4 /Users/office/_localhost/ca/vendor/craftcms/cms/src/db/Migration.php(49): verbb\formie\migrations\m220420_000000_stencil_add_entryid->safeUp()
#5 /Users/office/_localhost/ca/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#6 /Users/office/_localhost/ca/vendor/craftcms/cms/src/db/MigrationManager.php(149): craft\db\MigrationManager->migrateUp(Object(verbb\formie\migrations\m220420_000000_stencil_add_entryid))
#7 /Users/office/_localhost/ca/vendor/craftcms/cms/src/services/Updates.php(252): craft\db\MigrationManager->up()
#8 /Users/office/_localhost/ca/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(493): craft\services\Updates->runMigrations(Array)
#9 /Users/office/_localhost/ca/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#10 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#11 /Users/office/_localhost/ca/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /Users/office/_localhost/ca/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#13 /Users/office/_localhost/ca/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('migrate', Array)
#14 /Users/office/_localhost/ca/vendor/craftcms/cms/src/web/Application.php(307): yii\base\Module->runAction('updater/migrate', Array)
#15 /Users/office/_localhost/ca/vendor/craftcms/cms/src/web/Application.php(695): craft\web\Application->runAction('updater/migrate')
#16 /Users/office/_localhost/ca/vendor/craftcms/cms/src/web/Application.php(264): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#17 /Users/office/_localhost/ca/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /Users/office/_localhost/ca/web/index.php(23): yii\base\Application->run()
#19 {main}```

**Comment by alexanderbuergin** [comment]
Unfortunately, we have not yet found the error after several attempts. Can we send you the DB and you can see what you find?

**Comment by engram-design** [comment]
If you can send your database and `composer.json` and `composer.lock` files to `web@verbb.io` we can take a look!

**Comment by alexanderloewe** [comment]
Hello @engram-design 

I don't want to push, but is there an update on this issue yet?

**Comment by engram-design** [comment]
Sorry for the delay, just responded to your email directly.
