### ISSUE TITLE
Internal Server Error: A server error occurred. /cpresources/cb60d2b8/axios.js:1:23152

### ISSUE THREAD

**Issue by adrianjean** [verbb/formie#1966]
### Describe the bug

Having a strange issue.
When I duplicate an existing form, and try to edit it, I am getting an "axios.js" error in the CP and am unable to save the form:

```
Internal Server Error: A server error occurred.
AxiosError: Request failed with status code 500
at https://website.com/cpresources/cb60d2b8/axios.js?v=1719977756:1:23147
at XMLHttpRequest.S (https://website.com/cpresources/cb60d2b8/axios.js?v=1719977756:1:23292)
```

The reason I am duplicating the forms is because every so often a form will get corrupted, and throw an invalid parent error, so I duplicate the form to fix it.

The logs also show this:
```
Call to a member function setRows() on null {"trace":["#0 /srv/www/website.com/vendor/yiisoft/yii2/base/Component.php(180): verbb\\formie\\base\\NestedField->setRows()"
```

###
UPDATE:
- When I create a fresh form, everything works. 
- When I add a form to an entry using CKEditor, using an embedded entry, that references that form, then go back to edit that form in Formie, it causes this error:

```
[yii\base\InvalidConfigException] Invalid owner ID: 7855 {"trace":["#0 /srv/www/website.com//vendor/craftcms/cms/src/base/NestedElementTrait.php(203):...
```

- So I have to duplicate the form to have access to it again, causing the above problem.

### Steps to reproduce

1. Duplicate a form
2. Save the form

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

Craft Pro 5.2.5

### Plugin version

3.0.0-beta.16

### Multi-site?

Yes

**Comment by engram-design** [comment]
I can't seem to replicate the duplicate error, and the CKEditor issue seems an odd one, but I'll look into that!

**Comment by adrianjean** [comment]
I ended up exporting the forms and re-importing them as a temporary solution.

**Comment by samuelreichor** [comment]
@engram-design  We have the same error. If I can provide something to help you to reproduce it on your end, hit me up :)

**Comment by samuelreichor** [comment]
@engram-design Hm we fixed it by allowing apache to send the request :D That worked for us.

**Comment by adrianjean** [comment]
I forgot to come back and update this:

**Solution:** Running `php craft gc` from the command line seems to fix this issue.

**Comment by engram-design** [comment]
@adrianjean Appreciate the follow-up, thanks!
