### ISSUE TITLE
Export / Import   Craft 4 to Craft 5

### ISSUE THREAD

**Issue by wmdhosting** [verbb/formie#1995]
### Describe the bug

I exported  submission in Craft 4 and tryed to import with feedme to  Craft 5

And get this error.. 

Twig\Error\RuntimeError: Key "label" for array with keys "name, handle, default" does not exist. in /home/username/vendor/verbb/formie/src/templates/integrations/feedme/elements/map.html:112
Stack trace:
#0 /home/username/vendor/craftcms/cms/src/helpers/Template.php(148): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Array, 'label', Array, 'any', false, false, false, 112)
#1 /home/username/storage/runtime/compiled_templates/ad/ad633adfea9eb8862da60d9be77a6558.php(285): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Array, 'label', Array, 'any', false, false, false, 112)
#2 /home/username/vendor/twig/twig/src/Template.php(394): __TwigTemplate_3bf13bb7abd1d6b3bb2df403cd875aaf->doDisplay(Array, Array)
#3 /home/username/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#4 /home/username/storage/runtime/compiled_templates/f4/f4442c8126955f319aac443fe2823bb9.php(169): Twig\Template->display(Array)
#5 /home/username/vendor/twig/twig/src/Template.php(171): __TwigTemplate_e6f8bc268a032cd44c1c1ec219290949->block_content(Array, Array)
#6 /home/username/storage/runtime/compiled_templates/42/4246179cf9aa2dc74a5ea7ec226c17bd.php(645): Twig\Template->displayBlock('content', Array, Array)
#7 /home/username/vendor/twig/twig/src/Template.php(171): __TwigTemplate_90566532f0335afea11d1b6d7e3a3cd7->block_main(Array, Array)
#8 /home/username/storage/runtime/compiled_templates/42/4246179cf9aa2dc74a5ea7ec226c17bd.php(391): Twig\Template->displayBlock('main', Array, Array)
#9 /home/username/vendor/twig/twig/src/Template.php(171): __TwigTemplate_90566532f0335afea11d1b6d7e3a3cd7->block_body(Array, Array)
#10 /home/username/storage/runtime/compiled_templates/9c/9cd4269ff6bcac8e3f0beaaa431416c2.php(97): Twig\Template->displayBlock('body', Array, Array)
#11 /home/username/vendor/twig/twig/src/Template.php(394): __TwigTemplate_750fc71c1f82ab2d4417a1fc80312931->doDisplay(Array, Array)
#12 /home/username/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#13 /home/username/storage/runtime/compiled_templates/35/3538ec48a11def98bece0f5c696d49f9.php(56): Twig\Template->display(Array, Array)
#14 /home/username/vendor/twig/twig/src/Template.php(394): __TwigTemplate_2abcb1ccba806751f58d9f515188fe80->doDisplay(Array, Array)
#15 /home/username/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#16 /home/username/storage/runtime/compiled_templates/42/4246179cf9aa2dc74a5ea7ec226c17bd.php(170): Twig\Template->display(Array, Array)
#17 /home/username/vendor/twig/twig/src/Template.php(394): __TwigTemplate_90566532f0335afea11d1b6d7e3a3cd7->doDisplay(Array, Array)
#18 /home/username/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#19 /home/username/storage/runtime/compiled_templates/da/daafa9d09f171b6f2b59561af02b02ac.php(57): Twig\Template->display(Array, Array)
#20 /home/username/vendor/twig/twig/src/Template.php(394): __TwigTemplate_3adcfc42f2d891f7b46cf02519aebc0b->doDisplay(Array, Array)
#21 /home/username/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#22 /home/username/storage/runtime/compiled_templates/f4/f4442c8126955f319aac443fe2823bb9.php(79): Twig\Template->display(Array, Array)
#23 /home/username/vendor/twig/twig/src/Template.php(394): __TwigTemplate_e6f8bc268a032cd44c1c1ec219290949->doDisplay(Array, Array)
#24 /home/username/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#25 /home/username/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#26 /home/username/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render(Array)
#27 /home/username/vendor/twig/twig/src/Environment.php(280): Twig\TemplateWrapper->render(Array)
#28 /home/username/vendor/craftcms/cms/src/web/View.php(494): Twig\Environment->render('feed-me/feeds/_...', Array)
#29 /home/username/vendor/craftcms/cms/src/web/View.php(547): craft\web\View->renderTemplate('feed-me/feeds/_...', Array)
#30 /home/username/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\web\View->renderPageTemplate('feed-me/feeds/_...', Array, 'cp')
#31 /home/username/vendor/yiisoft/yii2/web/Response.php(1109): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#32 /home/username/vendor/craftcms/cms/src/web/Response.php(338): yii\web\Response->prepare()
#33 /home/username/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#34 /home/username/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#35 /home/username/public_html/index.php(24): yii\base\Application->run()
#36 {main}

### Steps to reproduce

1. Export in Craft 4
2. IMport in Craft 4

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Craft CMS version

5,2,8

### Plugin version

3.0.0-beta.18

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.18"`.

**Comment by wmdhosting** [comment]
thx for quick fix now no error.  but nothign is imported.. 

I get this.. 
![2024-07-30_07-10-57](https://github.com/user-attachments/assets/92e43418-93a8-4ebc-abad-24b6e827c3b7)

This is in queve log.. 

2024-07-30 07:10:16 [queue.ERROR] [feed-me] {"message":"`Call to a member function normalizeValue() on null - DefaultField.php: 65`.","feed":"Formie","key":"jtesxokvyxdweohjftfg"} {"memory":90945352} 
2024-07-30 07:10:16 [queue.ERROR] [Error] Call to a member function normalizeValue() on null {"trace":["#0 /home/username/vendor/verbb/formie/src/integrations/feedme/fields/BaseFieldTrait.php(20): craft\\feedme\\fields\\DefaultField->parseField()","#1 /home/username/vendor/verbb/formie/src/integrations/feedme/fields/BaseFieldTrait.php(20): verbb\\formie\\integrations\\feedme\\fields\\DefaultField->parseField()","#2 /home/username/vendor/craftcms/feed-me/src/services/Fields.php(234): verbb\\formie\\integrations\\feedme\\fields\\Email->parseField()","#3 /home/username/vendor/craftcms/feed-me/src/services/Process.php(405): craft\\feedme\\services\\Fields->parseField(Array, Object(verbb\\formie\\elements\\Submission), Array, 'emailAddress', Array)","#4 /home/username/vendor/craftcms/feed-me/src/queue/jobs/FeedImport.php(99): craft\\feedme\\services\\Process->processFeed(9, Array, Array)","#5 /home/username/vendor/yiisoft/yii2-queue/src/Queue.php(243): craft\\feedme\\queue\\jobs\\FeedImport->execute(Object(craft\\queue\\Queue))","#6 /home/username/vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\\queue\\Queue->handleMessage('351028', 'O:34:\"craft\\\\fee...', '9999', '1')","#7 /home/username/vendor/yiisoft/yii2-queue/src/cli/Command.php(146): yii\\queue\\cli\\Queue->execute('351028', 'O:34:\"craft\\\\fee...', '9999', '1', '22485')","#8 [internal function]: yii\\queue\\cli\\Command->actionExec('351028', '9999', '1', '22485')","#9 /home/username/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)","#10 /home/username/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams(Array)","#11 /home/username/vendor/yiisoft/yii2/console/Controller.php(180): yii\\base\\Controller->runAction('exec', Array)","#12 /home/username/vendor/craftcms/cms/src/console/ControllerTrait.php(89): yii\\console\\Controller->runAction('exec', Array)","#13 /home/username/vendor/yiisoft/yii2/base/Module.php(552): craft\\queue\\Command->runAction('exec', Array)","#14 /home/username/vendor/yiisoft/yii2/console/Application.php(180): yii\\base\\Module->runAction('queue/exec', Array)","#15 /home/username/vendor/craftcms/cms/src/console/Application.php(91): yii\\console\\Application->runAction('queue/exec', Array)","#16 /home/username/vendor/yiisoft/yii2/console/Application.php(147): craft\\console\\Application->runAction('queue/exec', Array)","#17 /home/username/vendor/craftcms/cms/src/console/Application.php(122): yii\\console\\Application->handleRequest(Object(craft\\console\\Request))","#18 /home/username/vendor/yiisoft/yii2/base/Application.php(384): craft\\console\\Application->handleRequest(Object(craft\\console\\Request))","#19 /home/username/craft(22): yii\\base\\Application->run()","#20 {main}"],"memory":90944624,"exception":"[object] (Error(code: 0): Call to a member function normalizeValue() on null at /home/username/vendor/craftcms/feed-me/src/fields/DefaultField.php:65)"}

**Comment by engram-design** [comment]
Just pushed another fix for that. Run `composer require verbb/formie:"dev-craft-5 as 3.0.0-beta.18"`.

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.20](https://github.com/verbb/formie/releases/tag/3.0.0-beta.20)
