### ISSUE TITLE
GraphQL schema issues with some software

### ISSUE THREAD

**Issue by jaydensmith** [verbb/formie#209]
I'm using the [JS GraphQL](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/) plugin for IntelliJ which seems to be stricter than, say, [GraphiQL](https://github.com/graphql/graphiql) when parsing the schema. Since the field interface update it has been unable to build a valid schema using the introspection result.

```
SchemaProblem{errors=[The object type 'Field_Address' [@-1:-1] has tried to redefine field 'limit' defined via interface 'FieldInterface' [@-1:-1] from 'Boolean' to 'String', The object type 'Field_Address' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String', The object type 'Field_Agree' [@-1:-1] has tried to redefine field 'limit' defined via interface 'FieldInterface' [@-1:-1] from 'Boolean' to 'String', The object type 'Field_Agree' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String', The object type 'Field_Agree' [@-1:-1] has tried to redefine field 'defaultValue' defined via interface 'FieldInterface' [@-1:-1] from 'String' to 'Boolean', The object type 'Field_Categories' [@-1:-1] has tried to redefine field 'limit' defined via interface 'FieldInterface' [@-1:-1] from 'Boolean' to 'String', The object type 'Field_Categories' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String', The object type 'Field_Checkboxes' [@-1:-1] has tried to redefine field 'limit' defined via interface 'FieldInterface' [@-1:-1] from 'Boolean' to 'String', The object type 'Field_Checkboxes' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String', The object type 'Field_Date' [@-1:-1] has tried to redefine field 'limit' defined via interface 'FieldInterface' [@-1:-1] from 'Boolean' to 'String', The object type 'Field_Date' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String', The object type 'Field_Date' [@-1:-1] has tried to redefine field 'defaultValue' defined via interface 'FieldInterface' [@-1:-1] from 'String' to 'DateTime', The object type 'Field_Dropdown' [@-1:-1] has tried to redefine field 'limit' defined via interface 'FieldInterface' [@-1:-1] from 'Boolean' to 'String', The object type 'Field_Dropdown' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String', The object type 'Field_Email' [@-1:-1] has tried to redefine field 'limit' defined via interface 'FieldInterface' [@-1:-1] from 'Boolean' to 'String', The object type 'Field_Email' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String', The object type 'Field_Entries' [@-1:-1] has tried to redefine field 'limit' defined via interface 'FieldInterface' [@-1:-1] from 'Boolean' to 'String', The object type 'Field_Entries' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String', The object type 'Field_FileUpload' [@-1:-1] has tried to redefine field 'limit' defined via interface 'FieldInterface' [@-1:-1] from 'Boolean' to 'String', The object type 'Field_FileUpload' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String', The object type 'Field_Group' [@-1:-1] has tried to redefine field 'limit' defined via interface 'FieldInterface' [@-1:-1] from 'Boolean' to 'String', The object type 'Field_Group' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String', The object type 'Field_Heading' [@-1:-1] has tried to redefine field 'limit' defined via interface 'FieldInterface' [@-1:-1] from 'Boolean' to 'String', The object type 'Field_Heading' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String', The object type 'Field_Hidden' [@-1:-1] has tried to redefine field 'limit' defined via interface 'FieldInterface' [@-1:-1] from 'Boolean' to 'String', The object type 'Field_Hidden' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String', The object type 'Field_Html' [@-1:-1] has tried to redefine field 'limit' defined via interface 'FieldInterface' [@-1:-1] from 'Boolean' to 'String', The object type 'Field_Html' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String', The object type 'Field_MissingField' [@-1:-1] has tried to redefine field 'limit' defined via interface 'FieldInterface' [@-1:-1] from 'Boolean' to 'String', The object type 'Field_MissingField' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String', The object type 'Field_MultiLineText' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String', The object type 'Field_Name' [@-1:-1] has tried to redefine field 'limit' defined via interface 'FieldInterface' [@-1:-1] from 'Boolean' to 'String', The object type 'Field_Name' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String', The object type 'Field_Number' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String', The object type 'Field_Phone' [@-1:-1] has tried to redefine field 'limit' defined via interface 'FieldInterface' [@-1:-1] from 'Boolean' to 'String', The object type 'Field_Phone' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String', The object type 'Field_Radio' [@-1:-1] has tried to redefine field 'limit' defined via interface 'FieldInterface' [@-1:-1] from 'Boolean' to 'String', The object type 'Field_Radio' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String', The object type 'Field_Recipients' [@-1:-1] has tried to redefine field 'limit' defined via interface 'FieldInterface' [@-1:-1] from 'Boolean' to 'String', The object type 'Field_Recipients' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String', The object type 'Field_Repeater' [@-1:-1] has tried to redefine field 'limit' defined via interface 'FieldInterface' [@-1:-1] from 'Boolean' to 'String', The object type 'Field_Repeater' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String', The object type 'Field_Section' [@-1:-1] has tried to redefine field 'limit' defined via interface 'FieldInterface' [@-1:-1] from 'Boolean' to 'String', The object type 'Field_Section' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String', The object type 'Field_SingleLineText' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String', The object type 'Field_Table' [@-1:-1] has tried to redefine field 'limit' defined via interface 'FieldInterface' [@-1:-1] from 'Boolean' to 'String', The object type 'Field_Table' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String', The object type 'Field_Tags' [@-1:-1] has tried to redefine field 'limit' defined via interface 'FieldInterface' [@-1:-1] from 'Boolean' to 'String', The object type 'Field_Tags' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String', The object type 'Field_Users' [@-1:-1] has tried to redefine field 'limit' defined via interface 'FieldInterface' [@-1:-1] from 'Boolean' to 'String', The object type 'Field_Users' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String', The object type 'Field_Products' [@-1:-1] has tried to redefine field 'limit' defined via interface 'FieldInterface' [@-1:-1] from 'Boolean' to 'String', The object type 'Field_Products' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String', The object type 'Field_Variants' [@-1:-1] has tried to redefine field 'limit' defined via interface 'FieldInterface' [@-1:-1] from 'Boolean' to 'String', The object type 'Field_Variants' [@-1:-1] has tried to redefine field 'limitAmount' defined via interface 'FieldInterface' [@-1:-1] from 'Int' to 'String']}
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:251)
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:227)
	at com.intellij.lang.jsgraphql.ide.editor.GraphQLIntrospectionService.buildIntrospectionSchema(GraphQLIntrospectionService.java:302)
	at com.intellij.lang.jsgraphql.ide.editor.GraphQLIntrospectionService.printIntrospectionAsGraphQL(GraphQLIntrospectionService.java:218)
	at com.intellij.lang.jsgraphql.ide.editor.GraphQLIntrospectionService$IntrospectionQueryTask.run(GraphQLIntrospectionService.java:475)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by engram-design** [comment]
Should be fixed in [1.3.3](https://github.com/verbb/formie/releases/tag/1.3.3)
