### ISSUE TITLE
Setting unknown property: verbb\formie\fields\Dropdown::nestedLayoutId

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#2151]
### Describe the bug

Sentry captured this error related to moving a dropdown field in the layout editor.

I am struggling to replicate the error again locally, the form it triggered on, has an address field and the dropdown field was moved to be in two columns i.e. alongside the field and then this triggered.

### Steps to reproduce

See description, sorry I can't be more specific.

### Form settings

- Multi-page form: No
- Submission Method: N/A
- Client-side Validation: N/A
- Custom Form Templates: N/A

### Craft CMS version

5.5.0.1

### Plugin version

3.0.12

### Additional context

```
yii\base\UnknownPropertyException: Setting unknown property: verbb\formie\fields\Dropdown::nestedLayoutId
#33 /var/task/vendor/yiisoft/yii2/base/Component.php(217): yii\base\Component::__set
#32 /var/task/vendor/craftcms/cms/src/helpers/App.php(1518): craft\helpers\App::configure
#31 /var/task/vendor/craftcms/cms/src/base/Model.php(84): craft\base\Model::__construct
#30 /var/task/vendor/verbb/formie/src/base/Field.php(264): verbb\formie\base\Field::__construct
#29 /var/task/vendor/verbb/formie/src/base/OptionsField.php(92): verbb\formie\base\OptionsField::__construct
#28 /var/task/vendor/verbb/formie/src/fields/Dropdown.php(58): verbb\formie\fields\Dropdown::__construct
#27 [internal](0): ReflectionClass::newInstanceArgs
#26 /var/task/vendor/yiisoft/yii2/di/Container.php(419): yii\di\Container::build
#25 /var/task/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container::get
#24 /var/task/vendor/yiisoft/yii2/BaseYii.php(365): yii\BaseYii::createObject
#23 /var/task/vendor/craftcms/cms/src/Craft.php(70): Craft::createObject
#22 /var/task/vendor/craftcms/cms/src/helpers/Component.php(142): craft\helpers\Component::createComponent
#21 /var/task/vendor/verbb/formie/src/services/Fields.php(433): verbb\formie\services\Fields::createField
#20 /var/task/vendor/verbb/formie/src/models/FieldLayoutRow.php(95): verbb\formie\models\FieldLayoutRow::setFields
#19 /var/task/vendor/yiisoft/yii2/base/Component.php(180): yii\base\Component::__set
#18 /var/task/vendor/craftcms/cms/src/helpers/App.php(1518): craft\helpers\App::configure
#17 /var/task/vendor/craftcms/cms/src/base/Model.php(84): craft\base\Model::__construct
#16 /var/task/vendor/verbb/formie/src/models/FieldLayoutPage.php(128): verbb\formie\models\FieldLayoutPage::setRows
#15 /var/task/vendor/yiisoft/yii2/base/Component.php(180): yii\base\Component::__set
#14 /var/task/vendor/craftcms/cms/src/helpers/App.php(1518): craft\helpers\App::configure
#13 /var/task/vendor/craftcms/cms/src/base/Model.php(84): craft\base\Model::__construct
#12 /var/task/vendor/verbb/formie/src/models/FieldLayoutPage.php(54): verbb\formie\models\FieldLayoutPage::__construct
#11 /var/task/vendor/verbb/formie/src/models/FieldLayout.php(71): verbb\formie\models\FieldLayout::setPages
#10 /var/task/vendor/verbb/formie/src/services/Forms.php(91): verbb\formie\services\Forms::buildFormFromPost
#9 /var/task/vendor/verbb/formie/src/controllers/FormsController.php(114): verbb\formie\controllers\FormsController::actionSave
#8 [internal](0): call_user_func_array
#7 /var/task/vendor/yiisoft/yii2/base/InlineAction.php(57): yii\base\InlineAction::runWithParams
#6 /var/task/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Controller::runAction
#5 /var/task/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Module::runAction
#4 /var/task/vendor/craftcms/cms/src/web/Application.php(350): craft\web\Application::runAction
#3 /var/task/vendor/craftcms/cms/src/web/Application.php(649): craft\web\Application::_processActionRequest
#2 /var/task/vendor/craftcms/cms/src/web/Application.php(312): craft\web\Application::handleRequest
#1 /var/task/vendor/yiisoft/yii2/base/Application.php(384): yii\base\Application::run
#0 /index.php(12): null
```

**Comment by engram-design** [comment]
The only reason I could see that happening is if there's a Group field you're also moving the Dropdown field in or out of. Would that be the case?

**Comment by jamesmacwhite** [comment]
I don't believe there was a group field on it, I went back through the stacktrace to confirm the form ID is was on and the layout doesn't have a group. I can't replicate locally either, so it is a bit odd.

**Comment by engram-design** [comment]
I'll do some testing on my end, but the `nestedLayoutId` is only ever used for Group/Repeater fields.

**Comment by jamesmacwhite** [comment]
Thanks. I'll try and replicate the issue with clearer info if I can as well.

**Comment by engram-design** [comment]
Updated in [4.0.0-beta.3](https://github.com/verbb/formie/releases/tag/4.0.0-beta.3).
