### ISSUE TITLE
Exception when running GC.

### ISSUE THREAD

**Issue by jaydensmith** [verbb/formie#241]
**Description**
Seems like there's a couple of imports are missing.

```
Exception 'Error' with message 'Class 'verbb\formie\services\DateInterval' not found'

in /Users/jaydensmith/public_html/xxx.com/vendor/verbb/formie/src/services/SentNotifications.php:152

Stack trace:
#0 /Users/jaydensmith/public_html/xxx.com/vendor/verbb/formie/src/Formie.php(283): verbb\formie\services\SentNotifications->pruneSentNotifications()
#1 [internal function]: verbb\formie\Formie->verbb\formie\{closure}(Object(yii\base\Event))
#2 /Users/jaydensmith/public_html/xxx.com/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(yii\base\Event))
#3 /Users/jaydensmith/public_html/xxx.com/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\services\\...', 'run', Object(yii\base\Event))
#4 /Users/jaydensmith/public_html/xxx.com/vendor/craftcms/cms/src/services/Gc.php(74): yii\base\Component->trigger('run')
#5 /Users/jaydensmith/public_html/xxx.com/vendor/craftcms/cms/src/console/controllers/GcController.php(56): craft\services\Gc->run(true)
#6 [internal function]: craft\console\controllers\GcController->actionRun()
#7 /Users/jaydensmith/public_html/xxx.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /Users/jaydensmith/public_html/xxx.com/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#9 /Users/jaydensmith/public_html/xxx.com/vendor/yiisoft/yii2/console/Controller.php(179): yii\base\Controller->runAction('', Array)
#10 /Users/jaydensmith/public_html/xxx.com/vendor/craftcms/cms/src/console/Controller.php(188): yii\console\Controller->runAction('', Array)
#11 /Users/jaydensmith/public_html/xxx.com/vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('', Array)
#12 /Users/jaydensmith/public_html/xxx.com/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('gc', Array)
#13 /Users/jaydensmith/public_html/xxx.com/vendor/craftcms/cms/src/console/Application.php(88): yii\console\Application->runAction('gc', Array)
#14 /Users/jaydensmith/public_html/xxx.com/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('gc', Array)
#15 /Users/jaydensmith/public_html/xxx.com/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#16 /Users/jaydensmith/public_html/xxx.com/craft(27): yii\base\Application->run()
#17 {main}
```

**Comment by engram-design** [comment]
Should be fixed in [1.3.3](https://github.com/verbb/formie/releases/tag/1.3.3)
