### ISSUE TITLE
Cant permanently delete forms

### ISSUE THREAD

**Issue by danieladarve** [verbb/formie#249]
**Description**
Deleting a form from the "trashed " screen returns
```
{"error":"SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'fmcd_testform' already exists\nThe SQL being executed was: RENAME TABLE `fmcd_testform` TO `fmcd_testform`"}

Stack trace:
#0 /Users/user/Development/craftcms/vendor/yiisoft/yii2/db/Command.php(1293): PDOStatement->execute()
#1 /Users/user/Development/craftcms/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute('RENAME TABLE `f...')
#2 /Users/user/Development/craftcms/vendor/craftcms/cms/src/helpers/MigrationHelper.php(174): yii\db\Command->execute()
#3 /Users/user/Development/craftcms/vendor/verbb/formie/src/services/Forms.php(243): craft\helpers\MigrationHelper::renameTable('{{%fmcd_testfor...', '{{%fmcd_testfor...')
#4 /Users/user/Development/craftcms/vendor/verbb/formie/src/elements/Form.php(1130): verbb\formie\services\Forms->deleteForm(Object(verbb\formie\elements\Form))
#5 /Users/user/Development/craftcms/vendor/craftcms/cms/src/services/Elements.php(1458): verbb\formie\elements\Form->beforeDelete()
#6 /Users/user/Development/craftcms/vendor/craftcms/cms/src/elements/actions/Delete.php(172): craft\services\Elements->deleteElement(Object(verbb\formie\elements\Form))
#7 /Users/user/Development/craftcms/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(230): craft\elements\actions\Delete->performAction(Object(verbb\formie\elements\db\FormQuery))
#8 [internal function]: craft\controllers\ElementIndexesController->actionPerformAction()
#9 /Users/user/Development/craftcms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /Users/user/Development/craftcms/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#11 /Users/user/Development/craftcms/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('perform-action', Array)
#12 /Users/user/Development/craftcms/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('perform-action', Array)
#13 /Users/user/Development/craftcms/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('element-indexes...', Array)
#14 /Users/user/Development/craftcms/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction('element-indexes...', Array)
#15 /Users/user/Development/craftcms/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#16 /Users/user/Development/craftcms/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /Users/user/Development/craftcms/web/index.php(22): yii\base\Application->run()
#18 /Users/user/.composer/vendor/laravel/valet/server.php(191): require('/Users/user...')
#19 {main}
```

**Steps to reproduce**
1. Try to delete a form from the trashed screen

### Form settings
Please pick from the options below.

- Multi-page form: Not Applicable
- Submission Method: Not Applicable
- Client-side Validation: Not Applicable
- Custom Form Templates: Not Applicable

**Additional info**
- Plugin version:  1.3.2
- Craft version: 3.5.16
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
Should be fixed in [1.3.3](https://github.com/verbb/formie/releases/tag/1.3.3)
