### ISSUE TITLE
Notification doesn't get send from the queue

### ISSUE THREAD

**Issue by Nielsvdel** [verbb/formie#621]
**Description**
The notification doesn't get send, i get the following error: Failed to send notification email: {"error":"Notification email “Notification name” could not be sent for submission “4390”. The mailer service failed to send the notification: “”."}. 

But when i go to the submission it self (/admin/formie/submissions/{formName}/{id}) and click on the "Send Email Notification" button is does work. 

I also tried to overwrite the From and Reply-To Email fields in the "Edit Notification" popup, but this also doesn't make a difference for the que. It still doesn't get send. 

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.4.22
- Craft version: 3.7.17.2
- Multi-site: No

**Comment by engram-design** [comment]
Are you able to share the queue information payload? There's something clearly going wrong when running the job via the queue. When sending the notification from editing the submission, it doesn't use the queue, so that's clearly the differentiating factor.

**Comment by Nielsvdel** [comment]
This is all the information i have from the failed notification in the que,
hope this is what your looking for.
Id 8453
Status Gefaald
Fout Failed to send notification email: {"error":"Notification email “Test
notificatie” could not be sent for submission “4390”. The mailer service
failed to send the notification: “”."}.
Voortgang 0%
Te reserveren tijd 300 seconden
Priority 1024
Pushed at 27 okt. 2021 09:05:04
Updated at 27 okt. 2021 09:05:05
Failed at 27 okt. 2021 09:05:05

Taakgegevens

{
    "submissionId": 4390,
    "submission": {
        "id": 4390,
        "formId": "4163",
        "statusId": "1",
        "userId": null,
        "ipAddress": null,
        "isIncomplete": "0",
        "isSpam": "0",
        "spamReason": null,
        "validateCurrentPageOnly": null,
        "tempId": null,
        "draftId": null,
        "revisionId": null,
        "isProvisionalDraft": false,
        "uid": "9e7428e1-03c2-4211-be79-7c158eb18646",
        "siteSettingsId": 4390,
        "fieldLayoutId": 44,
        "contentId": 2,
        "enabled": true,
        "archived": false,
        "siteId": 1,
        "title": "2021-10-27 09:05:04",
        "slug": null,
        "uri": null,
        "dateCreated": "2021-10-27T09:05:04+02:00",
        "dateUpdated": "2021-10-27T09:05:04+02:00",
        "dateLastMerged": null,
        "dateDeleted": null,
        "trashed": false,
        "isNewForSite": false,
        "canonicalId": 4390,
        "ref": null,
        "status": "new",
        "structureId": null,
        "url": null,
        "test": "test",
        "email": ***@***.***",
        "fields": [
            {
                "type": "verbb\\formie\\fields\\formfields\\SingleLineText",
                "handle": "test",
                "settings": {
                    "columnWidth": 12,
                    "limit": null,
                    "limitType": "characters",
                    "limitAmount": null,
                    "placeholder": null,
                    "defaultValue": null,
                    "prePopulate": null,
                    "errorMessage": null,
                    "labelPosition": "",
                    "instructionsPosition": "",
                    "cssClasses": null,
                    "containerAttributes": [],
                    "inputAttributes": [],
                    "includeInEmail": true,
                    "enableConditions": null,
                    "conditions":
"{\"showRule\":\"show\",\"conditionRule\":\"all\",\"conditions\":[]}",
                    "enableContentEncryption": false,
                    "visibility": "",
                    "formId": 4163,
                    "isNested": false
                },
                "value": "test"
            },
            {
                "type": "verbb\\formie\\fields\\formfields\\Email",
                "handle": "email",
                "settings": {
                    "validateDomain": false,
                    "blockedDomains": [],
                    "uniqueValue": false,
                    "columnWidth": 12,
                    "limit": null,
                    "limitType": "characters",
                    "limitAmount": null,
                    "placeholder": null,
                    "defaultValue": null,
                    "prePopulate": null,
                    "errorMessage": null,
                    "labelPosition": "",
                    "instructionsPosition": "",
                    "cssClasses": null,
                    "containerAttributes": [],
                    "inputAttributes": [],
                    "includeInEmail": true,
                    "enableConditions": null,
                    "conditions":
"{\"showRule\":\"show\",\"conditionRule\":\"all\",\"conditions\":[]}",
                    "enableContentEncryption": false,
                    "visibility": "",
                    "formId": 4163,
                    "isNested": false
                },
                "value": ***@***.***"
            }
        ]
    },
    "notificationId": "7",
    "notification": {
        "id": "7",
        "formId": "4163",
        "templateId": null,
        "name": "Test notificatie",
        "enabled": "1",
        "subject": "Test subject",
        "to": "{field.email}",
        "cc": null,
        "bcc": null,
        "replyTo": null,
        "replyToName": null,
        "from": null,
        "fromName": null,
        "content": "<p>{field.test}{field.email}</p>",
        "attachFiles": true,
        "enableConditions": false,
        "conditions":
"{\"sendRule\":\"send\",\"conditionRule\":\"all\",\"conditions\":[]}",
        "uid": "2eaf6614-13d2-4839-9855-87d8e69fde3a"
    },
    "email": {
        "charset": null,
        "from": {
            ***@***.***": "Bince"
        },
        "replyTo": null,
        "to": {
            ***@***.***": null
        },
        "cc": null,
        "bcc": null,
        "subject": "Test subject",
        "body": ***@***.***</p>"
    },
    "description": null
}

**Comment by engram-design** [comment]
Thanks for that, that does indeed seem pretty valid.

Would you mind commenting on:
- What service (if any) you're using to send emails
- How you're running the queue (using CLI, or running automatically)
- If this happens consistently, or just sometimes

**Comment by engram-design** [comment]
I should also mention the trying to change the "From" email and the "Recipient" email to be static, and not dynamic fields. This just helps to isolate whether its a field variable issue or not.

This error is unfortunately a generic "failed" message that comes from Craft's mailer service.

I'd also just check the `formie.log` log file, and any other log files, like the `queue.log`

**Comment by Nielsvdel** [comment]
- We use the services of Mailgun.
- The queue is running automatically
- And its happening consistently

The problem first occurred after we changed a setting in mailgun including a new endpoint. (EU server)

**Comment by engram-design** [comment]
What endpoint setting are you using? Aware you can't share the specifics - I've just never used the endpoint before.

**Comment by Nielsvdel** [comment]
https://api.eu.mailgun.net

**Comment by engram-design** [comment]
Thanks, I'll test that shortly, just in case that makes a difference. Wondering if in the meantime you could test with static values for From/Recipient and try to fire that through the queue?

**Comment by Nielsvdel** [comment]
I already tried that, it doesn't make a difference. The queue still gives the same error.

**Comment by engram-design** [comment]
I'm not quite sure how Mailgun's endpoint setting works. I've tried with `https://api.eu.mailgun.net` and that doesn't work even for Craft's email testing, or for submissions in the queue.

Using `https://api.mailgun.net` does work for me, but I'm not sure if that's because my account isn't based in the EU like yours might be.

But I can confirm I seem to get this issue when adding an incorrect endpoint.

**Comment by Nielsvdel** [comment]
When adding a new domain you have to choose the EU Domain region. Depending on what you choose you can use the corresponding endpoint.

**Comment by engram-design** [comment]
Ah, you're right. Been a while since we've used Mailgun, but just testing with that setup.

Have you consulted your Mailgun logs? An exact setup doesn't throw an error. But then I'm not testing with the same from/to emails as you've redacted them (which is fine), but I do know that if they aren't legitimate emails, some providers don't like that.

**Comment by Nielsvdel** [comment]
The mails from the queue don't even get to Mailgun, when we send it manualy (with the button in the submission itself) there is no issue. It seems like after our change that formie doesn't give the right information to the queue.

**Comment by engram-design** [comment]
Does this happen for local environments, or is it just on staging/production?

If local, I'm wondering if you might be able to do some debugging? For some reason, the Mailgun Swiftmailer transport doesn't return any error descriptions, like the local mailer transport does. In fact, it looks like the latest version of the `swiftmailer-mailgun-bundle` is actually out of date.

https://github.com/tehplague/swiftmailer-mailgun-bundle/blob/b77b8e405125df9c2ed35671819846fb1fcb2e3c/Service/MailgunTransport.php#L129-L138

The above includes the logging that we really need, but is for 2.0.0 version of that package. I might suggest the Craft team update their dependancy to reflect this change in version for the `cspoo/swiftmailer-mailgun-bundle` package.

Anyway - if you're up for adding some debug lines. If you can locate the following lines in `vendor/cspoo/swiftmailer-mailgun-bundle/Service/MailgunTransport.php`.

https://github.com/tehplague/swiftmailer-mailgun-bundle/blob/e54da0c7e4bb90609cc89d524bff56497ca2a664/Service/MailgunTransport.php#L111-L115

And change to:

```
} catch (\Exception $e) {
    $failedRecipients = $postData['to'];
    $sent = 0;
    $resultStatus = Swift_Events_SendEvent::RESULT_FAILED;

    // Temp added line
    throw new \Swift_TransportException($e->getMessage());
}
```

Then re-run a failed queue job. It should provide more information as the what exactly the error Mailgun is hitting.

**Comment by engram-design** [comment]
Also refer to Brandon's comment about the `v2` branch of the Mailgun plugin if you're interested https://github.com/craftcms/mailgun/issues/18#issuecomment-920293302

**Comment by Nielsvdel** [comment]
After debuggin we came across the following error: {"error":"Notification email "Notification Name" could not be sent for submission "4417". The mailer service failed to send the notification: "Swift_TransportException: Client error: `POST https://api.eu.mailgun.net/v3/mg.limesquare.nl/messages.mime` resulted in a `401 Unauthorized` response:\nForbidden\n in /home/forge/bince.nl/vendor/cspoo/swiftmailer-mailgun-bundle/Service/MailgunTransport.php:115\nStack trace:\n#0 /home/forge/bince.nl/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(71): cspoo\\Swiftmailer\\MailgunBundle\\Service\\MailgunTransport->send()\n#1 /home/forge/bince.nl/vendor/yiisoft/yii2-swiftmailer/src/Mailer.php(156): Swift_Mailer->send()\n#2 /home/forge/bince.nl/vendor/yiisoft/yii2/mail/BaseMailer.php(263): yii\\swiftmailer\\Mailer->sendMessage()\n#3 /home/forge/bince.nl/vendor/craftcms/cms/src/mail/Mailer.php(175): yii\\mail\\BaseMailer->send()\n#4 /home/forge/bince.nl/vendor/verbb/formie/src/services/Emails.php(305): craft\\mail\\Mailer->send()\n#5 /home/forge/bince.nl/vendor/verbb/formie/src/services/Submissions.php(196): verbb\\formie\\services\\Emails->sendEmail()\n#6 /home/forge/bince.nl/vendor/verbb/formie/src/jobs/SendNotification.php(67): verbb\\formie\\services\\Submissions->sendNotificationEmail()\n#7 /home/forge/bince.nl/vendor/yiisoft/yii2-queue/src/Queue.php(246): verbb\\formie\\jobs\\SendNotification->execute()\n#8 /home/forge/bince.nl/vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\\queue\\Queue->handleMessage()\n#9 /home/forge/bince.nl/vendor/yiisoft/yii2-queue/src/cli/Command.php(146): yii\\queue\\cli\\Queue->execute()\n#10 [internal function]: yii\\queue\\cli\\Command->actionExec()\n#11 /home/forge/bince.nl/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()\n#12 /home/forge/bince.nl/vendor/yiisoft/yii2/base/Controller.php(181): yii\\base\\InlineAction->runWithParams()\n#13 /home/forge/bince.nl/vendor/yiisoft/yii2/console/Controller.php(184): yii\\base\\Controller->runAction()\n#14 /home/forge/bince.nl/vendor/yiisoft/yii2/base/Module.php(534): yii\\console\\Controller->runAction()\n#15 /home/forge/bince.nl/vendor/yiisoft/yii2/console/Application.php(181): yii\\base\\Module->runAction()\n#16 /home/forge/bince.nl/vendor/craftcms/cms/src/console/Application.php(89): yii\\console\\Application->runAction()\n#17 /home/forge/bince.nl/vendor/yiisoft/yii2/console/Application.php(148): craft\\console\\Application->runAction()\n#18 /home/forge/bince.nl/vendor/yiisoft/yii2/base/Application.php(392): yii\\console\\Application->handleRequest()\n#19 /home/forge/bince.nl/craft(23): yii\\base\\Application->run()\n#20 {main}"."}

We tried with the “./craft mailer/test --to=e-mailaddress” to send a system mail and when we send those there is no error

**Comment by engram-design** [comment]
So the only way I could replicate the `401 Unauthorized response: Forbidden` response was to use incorrect API details. But that seems odd, as you can send emails okay, when not in the queue (sending from a submission edit page).

How're you setting your email settings, through `.env` variables, or hard-coded in the control panel? I'm wondering if you might try the adverse approach to whatever you might be doing.

I've seen instances where things like PHP constants defined in the `web/index.php` are being used, but because they don't exist for a queue-run instance, the variables aren't available. I'm wondering if it might be a similar scenario, even if you're not doing specifically that.

I would suggest also testing the API details in that function just as a sanity check.

```
// Test the API Key
throw new \Swift_TransportException(print_r($this->mailgun, true));

// Test the Domain
throw new \Swift_TransportException($this->getDomain($message));
```

**Comment by Nielsvdel** [comment]
We run `php craft queue/listen` with 3 deamons. We tested it on production without a queue and then there is no issue. So it seems like the problem is with the deamon. Maybe you can reproduce it with a deamon?

**Comment by engram-design** [comment]
Yep, running from a daemon still works for me with valid credentials, so it must be something to do with your queue job setup, or your email settings.

Can you comment on how your email settings are set?

**Comment by engram-design** [comment]
Just wanted to check in on your email settings, and if you're using .env variables, or just inputting them in. Also feel free to ping me on the Craft Discord (username `crawf`) if that'll be easier to figure this one out. There's something clearly queue-specific (or CLI-specific) that's causing this behaviour.

**Comment by engram-design** [comment]
Closing due to inactivity
