### ISSUE TITLE
Post request required

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [verbb/formie#705]
We just updated to 1.5.4 and received this error:

```
Failed to load resource: the server responded with a status of 500 () /index.php/admin/actions/formie/forms/save
```

When you click on that `index.php/admin/actions/formie/forms/save` link in the console you get this:

![Screen Shot 2022-01-06 at 3 06 17 PM](https://user-images.githubusercontent.com/39201467/148459017-e8e73929-8f97-49b8-b2ee-40ee8c2d8c08.png)

That happens any time you simply try to save the form.

**Steps to reproduce**
1. Save a form
2. Click `index.php/admin/actions/formie/forms/save` in the console.

### Form settings
Please pick from the options below.

- Multi-page form:  No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.5.4
- Craft version: 3.7.28
- Multi-site: No

Thanks for the help!

Here's the full stack trace if you need it:

```

yii\web\BadRequestHttpException: Post request required in /var/www/project/cms/vendor/craftcms/cms/src/web/Controller.php:317
Stack trace:
#0 /var/www/project/cms/vendor/verbb/formie/src/controllers/FormsController.php(131): craft\web\Controller->requirePostRequest()
#1 [internal function]: verbb\formie\controllers\FormsController->actionSave()
#2 /var/www/project/cms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /var/www/project/cms/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#4 /var/www/project/cms/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('save', Array)
#5 /var/www/project/cms/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction('formie/forms/sa...', Array)
#6 /var/www/project/cms/vendor/craftcms/cms/src/web/Application.php(596): craft\web\Application->runAction('formie/forms/sa...', Array)
#7 /var/www/project/cms/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#8 /var/www/project/cms/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /var/www/project/cms/web/index.php(21): yii\base\Application->run()
#10 {main}
Copy StacktraceSearch StackoverflowSearch GoogleException
HTTP 400 – Bad Request – yii\web\BadRequestHttpException
Post request required
1. in /var/www/project/cms/vendor/craftcms/cms/src/web/Controller.phpat line 317
308309310311312313314315316317318319320321322323324325326 
    /**
     * Throws a 400 error if this isn’t a POST request
     *
     * @throws BadRequestHttpException if the request is not a post request
     */
    public function requirePostRequest()
    {
        if (!$this->request->getIsPost()) {
            throw new BadRequestHttpException('Post request required');
        }
    }
 
    /**
     * Throws a 400 error if the request doesn't accept JSON.
     *
     * @throws BadRequestHttpException if the request doesn't accept JSON
     */
    public function requireAcceptsJson()
2. in /var/www/project/cms/vendor/verbb/formie/src/controllers/FormsController.php at line 131– craft\web\Controller::requirePostRequest()
125126127128129130131132133134135136137     *
     * @return Response|null
     * @throws Throwable
     */
    public function actionSave()
    {
        $this->requirePostRequest();
        $request = Craft::$app->getRequest();
        $settings = Formie::$plugin->getSettings();
 
        $form = Formie::$plugin->getForms()->buildFormFromPost();
        $duplicate = $request->getParam('duplicate');
 
3. verbb\formie\controllers\FormsController::actionSave()
4. in /var/www/project/cms/vendor/yiisoft/yii2/base/InlineAction.php at line 57– call_user_func_array([verbb\formie\controllers\FormsController, 'actionSave'], [])
5. in /var/www/project/cms/vendor/yiisoft/yii2/base/Controller.php at line 178– yii\base\InlineAction::runWithParams([])
6. in /var/www/project/cms/vendor/yiisoft/yii2/base/Module.php at line 552– yii\base\Controller::runAction('save', [])
7. in /var/www/project/cms/vendor/craftcms/cms/src/web/Application.php at line 287– yii\base\Module::runAction('formie/forms/save', [])
281282283284285286287288289290291292293     * @param string $route
     * @param array $params
     * @return Response|null The result of the action, normalized into a Response object
     */
    public function runAction($route, $params = [])
    {
        $result = parent::runAction($route, $params);
 
        if ($result !== null) {
            if ($result instanceof Response) {
                return $result;
            }
 
8. in /var/www/project/cms/vendor/craftcms/cms/src/web/Application.php at line 596– craft\web\Application::runAction('formie/forms/save', [])
590591592593594595596597598599600601602        if ($request->getIsActionRequest()) {
            $route = implode('/', $request->getActionSegments());
 
            try {
                Craft::debug("Route requested: '$route'", __METHOD__);
                $this->requestedRoute = $route;
                return $this->runAction($route, $_GET);
            } catch (\Throwable $e) {
                $this->_unregisterDebugModule();
                if ($e instanceof InvalidRouteException) {
                    throw new NotFoundHttpException(Craft::t('yii', 'Page not found.'), $e->getCode(), $e);
                }
                throw $e;
9. in /var/www/project/cms/vendor/craftcms/cms/src/web/Application.php at line 266– craft\web\Application::_processActionRequest(craft\web\Request)
260261262263264265266267268269270271272                    throw new ForbiddenHttpException();
                }
            }
        }
 
        // If this is an action request, call the controller
        if (($response = $this->_processActionRequest($request)) !== null) {
            return $response;
        }
 
        // If we're still here, finally let Yii do it's thing.
        try {
            return parent::handleRequest($request);
10. in /var/www/project/cms/vendor/yiisoft/yii2/base/Application.php at line 384– craft\web\Application::handleRequest(craft\web\Request)
11. in /var/www/project/cms/web/index.php at line 21– yii\base\Application::run()
15161718192021    Dotenv\Dotenv::create(CRAFT_BASE_PATH)->load();
}
 
// Load and run Craft
define('CRAFT_ENVIRONMENT', getenv('ENVIRONMENT') ?: 'production');
$app = require CRAFT_VENDOR_PATH.'/craftcms/cms/bootstrap/web.php';
$app->run();
$_COOKIE = [
    '1031b8c41dfff97a311a7ac99863bdc5_username' => '1dd2a59522bac5058567d3285d99c415ed5baed40d388926dde1c6544ca52d8ca:2:{i:0;s:41:"1031b8c41dfff97a311a7ac99863bdc5_username";i:1;s:23:"hi@hybridinteractive.io";}',
    'critical-css' => '38d58cdd16de52ebf0f1',
    'CRAFT_CSRF_TOKEN' => '423c614487ff7241f4018ab8985721e91e4c260b82aa11c68cdfa713433e9a2ca:2:{i:0;s:16:"CRAFT_CSRF_TOKEN";i:1;s:208:"cX3V-Jpko7mSpZ5wAknkLlfVwCo_qZ-sH9HmPi01|333427a6618bb92f75972c1514f17253605d007573bc4e68363d65c91b56320ecX3V-Jpko7mSpZ5wAknkLlfVwCo_qZ-sH9HmPi01|1|$2y$13$e/D9wRmbIE91QcPCemynbu0lltPCT61MCzouxD3dRzyZlcW.P6k2S";}',
    'CraftSessionId' => 'ab3604f6809850681528b77b1e516068',
    '1031b8c41dfff97a311a7ac99863bdc5_identity' => 'c8254aec234c51dd8ec03abb767a69a2b0ce3d01f6aa9eee17b17dbd7d2d5026a:2:{i:0;s:41:"1031b8c41dfff97a311a7ac99863bdc5_identity";i:1;s:159:"[1,"[\\"cMNdTqTGZnbQWKmiSKx5axv8NhqYk3KrKjQe-sT_733jLcXKBf0UwoQfWQA6QJpdUs_2OJBaJcNkcuK4ufpfJfJwumCcJTzWOTdy\\",null,\\"8ffec38781748c07c6d2e71b451e2e28\\"]",3600]";}',
];

$_SESSION = [
    'bd62416aa8538ede709019a5e113eea5__flash' => [],
    '1031b8c41dfff97a311a7ac99863bdc5__token' => 'cMNdTqTGZnbQWKmiSKx5axv8NhqYk3KrKjQe-sT_733jLcXKBf0UwoQfWQA6QJpdUs_2OJBaJcNkcuK4ufpfJfJwumCcJTzWOTdy',
    '1031b8c41dfff97a311a7ac99863bdc5__id' => 1,
    '__authKey' => '["cMNdTqTGZnbQWKmiSKx5axv8NhqYk3KrKjQe-sT_733jLcXKBf0UwoQfWQA6QJpdUs_2OJBaJcNkcuK4ufpfJfJwumCcJTzWOTdy",null,"8ffec38781748c07c6d2e71b451e2e28"]',
    '1031b8c41dfff97a311a7ac99863bdc5__expire' => 1641510672,
    '__duration' => 3600,
];
Yii Framework
2022-01-06, 15:11:12

nginx/1.19.10

Yii Framework/2.0.44
```

**Comment by engram-design** [comment]
This _might_ be related to https://github.com/verbb/formie/issues/700, so worth a shot updating to the latest branch, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.5.4",
  "...": "..."
}
```

Then run `composer update`.

**Comment by DynamiteGoesBoom** [comment]
@engram-design That looks like it worked, thanks for the uber fast response time! Not that I'm surprised, because you and your team rocks!
