### ISSUE TITLE
User uploads wont attach to email notifications

### ISSUE THREAD

**Issue by mylesthedev** [verbb/formie#722]
**Description**
When enabling the attachments on the email notification the notification isn't sent due to a Swiftmailer issue.
It seems it can't open the file to read it?

The stack trace is below but doesn't really point to anything particular.

We are using local storage for this site and the path to the volume is `./assets`. The url to the volume is `/assets`.

```
2022-01-20 15:58:39 [-][-][-][error][formie] Notification email “TEST” could not be sent for submission “131960”. The mailer service failed to send the notification: “Swift_IoException: Unable to open file for reading [assets/form-uploads/Screen-Shot-2021-12-22-at-3.36.00-PM_2022-01-20-025829_kecb.png] in /app/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php:131
Stack trace:
#0 /app/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php(77): Swift_ByteStream_FileByteStream->getReadHandle()
#1 /app/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/ContentEncoder/Base64ContentEncoder.php(40): Swift_ByteStream_FileByteStream->read(8192)
#2 /app/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php(555): Swift_Mime_ContentEncoder_Base64ContentEncoder->encodeByteStream(Object(Swift_ByteStream_FileByteStream), Object(Swift_Transport_StreamBuffer), 0, 76)
#3 /app/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php(532): Swift_Mime_SimpleMimeEntity->bodyToByteStream(Object(Swift_Transport_StreamBuffer))
#4 /app/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php(570): Swift_Mime_SimpleMimeEntity->toByteStream(Object(Swift_Transport_StreamBuffer))
#5 /app/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php(532): Swift_Mime_SimpleMimeEntity->bodyToByteStream(Object(Swift_Transport_StreamBuffer))
#6 /app/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php(604): Swift_Mime_SimpleMimeEntity->toByteStream(Object(Swift_Transport_StreamBuffer))
#7 /app/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Message.php(162): Swift_Mime_SimpleMessage->toByteStream(Object(Swift_Transport_StreamBuffer))
#8 /app/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(400): Swift_Message->toByteStream(Object(Swift_Transport_StreamBuffer))
#9 /app/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(502): Swift_Transport_AbstractSmtpTransport->streamMessage(Object(Swift_Message))
#10 /app/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(518): Swift_Transport_AbstractSmtpTransport->doMailTransaction(Object(Swift_Message), 'info@christscol...', Array, Array)
#11 /app/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(206): Swift_Transport_AbstractSmtpTransport->sendTo(Object(Swift_Message), 'info@christscol...', Array, Array)
#12 /app/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(71): Swift_Transport_AbstractSmtpTransport->send(Object(Swift_Message), Array)
#13 /app/vendor/yiisoft/yii2-swiftmailer/src/Mailer.php(155): Swift_Mailer->send(Object(Swift_Message))
#14 /app/vendor/yiisoft/yii2/mail/BaseMailer.php(263): yii\swiftmailer\Mailer->sendMessage(Object(craft\mail\Message))
#15 /app/vendor/craftcms/cms/src/mail/Mailer.php(175): yii\mail\BaseMailer->send(Object(craft\mail\Message))
#16 /app/vendor/verbb/formie/src/services/Emails.php(368): craft\mail\Mailer->send(Object(craft\mail\Message))
#17 /app/vendor/verbb/formie/src/services/Submissions.php(197): verbb\formie\services\Emails->sendEmail(Object(verbb\formie\models\Notification), Object(verbb\formie\elements\Submission), Object(verbb\formie\jobs\SendNotification))
#18 /app/vendor/verbb/formie/src/jobs/SendNotification.php(67): verbb\formie\services\Submissions->sendNotificationEmail(Object(verbb\formie\models\Notification), Object(verbb\formie\elements\Submission), Object(verbb\formie\jobs\SendNotification))
#19 /app/vendor/yiisoft/yii2-queue/src/Queue.php(246): verbb\formie\jobs\SendNotification->execute(Object(craft\queue\Queue))
#20 /app/vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\queue\Queue->handleMessage('36763', 'O:34:"verbb\\for...', '300', '1')
#21 /app/vendor/yiisoft/yii2-queue/src/cli/Command.php(146): yii\queue\cli\Queue->execute('36763', 'O:34:"verbb\\for...', '300', '1', '22')
#22 [internal function]: yii\queue\cli\Command->actionExec('36763', '300', '1', '22')
#23 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#24 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#25 /app/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('exec', Array)
#26 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('exec', Array)
#27 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/exec', Array)
#28 /app/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('queue/exec', Array)
#29 /app/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('queue/exec', Array)
#30 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(craft\console\Request))
#31 /app/craft(22): yii\base\Application->run()
#32 {main}”.
```

**Steps to reproduce**
1. add file upload field to form
2. create email notification to include attachments
3. submit form to see if notification is triggered

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: tried both
- Client-side Validation: Yes
- Custom Form Templates: tried both

**Additional info**
- Plugin version: 1.5.7 (also tried 1.4.*)
- Craft version: 3.7.29 (also tried earlier versions)
- Multi-site: No

**Comment by engram-design** [comment]
Hmm, are you able to confirm if that file/path exists? And to ensure its not a corrupted upload (0kb)?

**Comment by mylesthedev** [comment]
Strange huh? Yup file path exists and isn't corrupt. Tried many different files as well.
What volume path settings do you normally use?

**Comment by engram-design** [comment]
Ah, that might be it. We always use full path/URLs, using `@web/assets` and `@webroot/assets` for the URL and path respectively. Because you're using `./` as the path, it's probably trying to get the file from the current directory, which would be `/app/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/assets/form-uploads/Screen-Shot-2021-12-22-at-3.36.00-PM_2022-01-20-025829_kecb.png`

**Comment by mylesthedev** [comment]
Yup that did the trick! Thanks @engram-design for the help :)
