### ISSUE TITLE
Typed property $expectedType exception

### ISSUE THREAD

**Issue by ccchapman** [verbb/formie#820]
**Description**

```
{
	"errors": [
		{
			"message": "Typed property verbb\\formie\\fields\\formfields\\MissingField::$expectedType must not be accessed before initialization"
		}
	]
}
```

```
[2022-04-05T20:07:16.894134+00:00] web.ERROR: Error: Typed property verbb\formie\fields\formfields\MissingField::$expectedType must not be accessed before initialization in /srv/cms.dev.project/vendor/craftcms/cms/src/base/ConfigurableComponent.php:65
Stack trace:
#0 /srv/cms.dev.project/vendor/verbb/formie/src/base/FormFieldTrait.php(1048): craft\base\ConfigurableComponent->getSettings()
#1 /srv/cms.dev.project/vendor/verbb/formie/src/gql/types/generators/FieldGenerator.php(39): verbb\formie\base\FormField->getSettingGqlTypes()
#2 /srv/cms.dev.project/vendor/verbb/formie/src/gql/interfaces/FieldInterface.php(40): verbb\formie\gql\types\generators\FieldGenerator::generateTypes()
#3 /srv/cms.dev.project/vendor/verbb/formie/src/gql/interfaces/RowInterface.php(53): verbb\formie\gql\interfaces\FieldInterface::getType()
#4 /srv/cms.dev.project/vendor/verbb/formie/src/gql/types/generators/RowGenerator.php(21): verbb\formie\gql\interfaces\RowInterface::getFieldDefinitions()
#5 /srv/cms.dev.project/vendor/verbb/formie/src/gql/interfaces/RowInterface.php(38): verbb\formie\gql\types\generators\RowGenerator::generateTypes()
#6 /srv/cms.dev.project/vendor/verbb/formie/src/gql/interfaces/PageInterface.php(59): verbb\formie\gql\interfaces\RowInterface::getType()
#7 /srv/cms.dev.project/vendor/verbb/formie/src/gql/types/generators/PageGenerator.php(21): verbb\formie\gql\interfaces\PageInterface::getFieldDefinitions()
#8 /srv/cms.dev.project/vendor/craftcms/cms/src/services/Gql.php(379): verbb\formie\gql\types\generators\PageGenerator::generateTypes()
#9 /srv/cms.dev.project/vendor/craftcms/cms/src/services/Gql.php(493): craft\services\Gql->getSchemaDef(Object(craft\models\GqlSchema), true)
#10 /srv/cms.dev.project/vendor/craftcms/cms/src/controllers/GraphqlController.php(177): craft\services\Gql->executeQuery(Object(craft\models\GqlSchema), '\n    query Intr...', NULL, NULL, true)
#11 [internal function]: craft\controllers\GraphqlController->actionApi()
#12 /srv/cms.dev.project/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /srv/cms.dev.project/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#14 /srv/cms.dev.project/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('api', Array)
#15 /srv/cms.dev.project/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('graphql/api', Array)
#16 /srv/cms.dev.project/vendor/craftcms/cms/src/web/Application.php(621): craft\web\Application->runAction('graphql/api', Array)
#17 /srv/cms.dev.project/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#18 /srv/cms.dev.project/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /srv/cms.dev.project/web/index.php(12): yii\base\Application->run()
#20 {main}
```

**Steps to reproduce**
1. Install and enable Formie 87cf1282b555b5f0e7a87243a73aa3dc7420f1e4 on Craft 4
2. Visit GraphiQL and view XHR response for `/index.php?p=admin/actions/graphql/api&site=default`

**Additional info**
- Plugin version: 87cf1282b555b5f0e7a87243a73aa3dc7420f1e4
- Craft version: 4
- Multi-site: Yes

**Additional context**

**Comment by engram-design** [comment]
I did notice this, but because this is an inherited trait from [craft\base\MissingComponentTrait](https://github.com/craftcms/cms/blob/4cf5fe7263bd0ef50cdf04da29a8d924d1d87fdc/src/base/MissingComponentTrait.php#L27) I figure this should be fixed in Craft 4.

See https://github.com/craftcms/cms/pull/10866

**Comment by engram-design** [comment]
Should be fixed for the next Formie beta https://github.com/verbb/formie/commit/56890096ab6bf50cf7eed341fa6680a4116935cc

**Comment by ccchapman** [comment]
Verified. Thanks!
