### ISSUE TITLE
Crash when editing form ("Return value must be of type array, ...MemoizableArray returned")

### ISSUE THREAD

**Issue by tremby** [verbb/formie#864]
**Description**

Since updating to the latest version I get a crashing error when attempting to edit a form.

**Steps to reproduce**
1. Attempt to edit a form, it doesn't seem to matter which one
2. See error

```
TypeError: verbb\formie\services\Notifications::getFormNotifications(): Return value must be of type array, craft\base\MemoizableArray returned in /srv/my-project/vendor/verbb/formie/src/services/Notifications.php:69
Stack trace:
#0 /srv/my-project/vendor/verbb/formie/src/elements/Form.php(1134): verbb\formie\services\Notifications->getFormNotifications(Object(verbb\formie\elements\Form))
#1 /srv/my-project/vendor/verbb/formie/src/controllers/FormsController.php(531): verbb\formie\elements\Form->getNotifications()
#2 /srv/my-project/vendor/verbb/formie/src/controllers/FormsController.php(102): verbb\formie\controllers\FormsController->_prepareVariableArray(Array)
#3 [internal function]: verbb\formie\controllers\FormsController->actionEdit(172, NULL, NULL)
#4 /srv/my-project/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /srv/my-project/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#6 /srv/my-project/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('edit', Array)
#7 /srv/my-project/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('formie/forms/ed...', Array)
#8 /srv/my-project/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('formie/forms/ed...', Array)
#9 /srv/my-project/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#10 /srv/my-project/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#11 /srv/my-project/web/index.php(12): yii\base\Application->run()
#12 {main}
```

### Form settings
Please pick from the options below.

- Multi-page form: n/a
- Submission Method: n/a
- Client-side Validation: n/a
- Custom Form Templates: n/a

**Additional info**
- Plugin version: dev-craft-4 7d8ccd2
- Craft version: 4.0.x-dev cfab4fc
- Multi-site: Yes

**Additional context**

**Comment by engram-design** [comment]
Fixed in [2.0.0-beta.4](https://github.com/verbb/formie/releases/tag/2.0.0-beta.4)
