### ISSUE TITLE
Salesforce Integration / Token is null

### ISSUE THREAD

**Issue by giorgiopogliani** [verbb/formie#906]
**Description**

The Salesforce App seems to have all the needed settings as explained in the integration settings. 

```
2022-05-27 10:14:47 [-][-][-][info][craft\queue\QueueLogBehavior::beforeExec]  [746688] Triggering form “salesforce” integration. (attempt: 1, pid: 121) - Started
2022-05-27 10:14:48 [-][-][-][error][formie] Salesforce: API error: “verbb\formie\services\Tokens::refreshToken(): Argument #1 ($token) must be of type verbb\formie\models\Token, null given, called in /app/vendor/verbb/formie/src/integrations/crm/Salesforce.php on line 493” /app/vendor/verbb/formie/src/services/Tokens.php:140
2022-05-27 10:14:48 [-][-][-][error][formie] Salesforce: API error: “Call to undefined method TypeError::getResponse()” /app/vendor/verbb/formie/src/integrations/crm/Salesforce.php:390
2022-05-27 10:14:48 [-][-][-][error][craft\queue\QueueLogBehavior::afterError]  [746688] Triggering form “salesforce” integration. (attempt: 1, pid: 121) - Error (time: 0.444s): API error: “Call to undefined method TypeError::getResponse()” /app/vendor/verbb/formie/src/integrations/crm/Salesforce.php:390
2022-05-27 10:14:48 [-][-][-][error][verbb\formie\errors\IntegrationException] verbb\formie\errors\IntegrationException: API error: “Call to undefined method TypeError::getResponse()” /app/vendor/verbb/formie/src/integrations/crm/Salesforce.php:390 in /app/vendor/verbb/formie/src/base/Integration.php:173
Stack trace:
#0 /app/vendor/verbb/formie/src/integrations/crm/Salesforce.php(459): verbb\formie\base\Integration::apiError(Object(verbb\formie\integrations\crm\Salesforce), Object(Error))
#1 /app/vendor/verbb/formie/src/services/Submissions.php(260): verbb\formie\integrations\crm\Salesforce->sendPayload(Object(verbb\formie\elements\Submission))
#2 /app/vendor/verbb/formie/src/jobs/TriggerIntegration.php(58): verbb\formie\services\Submissions->sendIntegrationPayload(Object(verbb\formie\integrations\crm\Salesforce), Object(verbb\formie\elements\Submission))
#3 /app/vendor/yiisoft/yii2-queue/src/Queue.php(246): verbb\formie\jobs\TriggerIntegration->execute(Object(craft\queue\Queue))
#4 /app/vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\queue\Queue->handleMessage('746688', 'O:36:"verbb\\for...', '3600', '1')
#5 /app/vendor/yiisoft/yii2-queue/src/cli/Command.php(146): yii\queue\cli\Queue->execute('746688', 'O:36:"verbb\\for...', '3600', '1', '121')
#6 [internal function]: yii\queue\cli\Command->actionExec('746688', '3600', '1', '121')
#7 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#9 /app/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('exec', Array)
#10 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('exec', Array)
#11 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/exec', Array)
#12 /app/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('queue/exec', Array)
#13 /app/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('queue/exec', Array)
#14 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(craft\console\Request))
#15 /app/craft(22): yii\base\Application->run()
#16 {main}
```

**Steps to reproduce**
1. The integrations connects successfully.
2. Sending a submission with mapToLead option failed with the error.

### Form settings
- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: 1.5.17
- Craft version: 3.7.27.2
- Multi-site: Yes

**Comment by engram-design** [comment]
Did you manage to fix this yourself? Usually, this means that the provider needs to be disconnected and reconnected. The error message has improved in Formie v2 however.

**Comment by giorgiopogliani** [comment]
Yeah, basically I kept trying the failed jobs after I updated the credentials in the integrations. Then, I discovered that the `tokenId` is serialized in the job data. Thanks!
